// Automatically generated by parse-reports.js
window.reportsData = {
  "광주수완": {
    "totalInfluencers": 3,
    "totalContents": 3,
    "totalViews": 126,
    "averageViews": 42,
    "mobileViews": 61,
    "pcViews": 65,
    "mobileRatio": 48,
    "pcRatio": 52,
    "averageMobileViews": 20,
    "averagePcViews": 22,
    "dailyData": [
      {
        "date": "2026-06-02",
        "day": "화",
        "pc": 12,
        "mobile": 8,
        "total": 20
      },
      {
        "date": "2026-06-03",
        "day": "수",
        "pc": 9,
        "mobile": 16,
        "total": 25
      },
      {
        "date": "2026-06-04",
        "day": "목",
        "pc": 8,
        "mobile": 8,
        "total": 16
      },
      {
        "date": "2026-06-05",
        "day": "금",
        "pc": 10,
        "mobile": 5,
        "total": 15
      },
      {
        "date": "2026-06-06",
        "day": "토",
        "pc": 10,
        "mobile": 5,
        "total": 15
      },
      {
        "date": "2026-06-07",
        "day": "일",
        "pc": 7,
        "mobile": 9,
        "total": 16
      },
      {
        "date": "2026-06-08",
        "day": "월",
        "pc": 4,
        "mobile": 8,
        "total": 12
      },
      {
        "date": "2026-06-09",
        "day": "화",
        "pc": 5,
        "mobile": 2,
        "total": 7
      }
    ],
    "contents": [
      {
        "title": "수완지구 이투스247학원 광주 독학관리 잘 하는 곳",
        "blogger": "yyiyuhyun",
        "date": "2026-06-02",
        "likes": 3,
        "comments": 1,
        "url": "https://blog.naver.com/yyiyuhyun/224303573025"
      },
      {
        "title": "광주 독학관리 반수학원 이투스247학원 광주수완점",
        "blogger": "judy13",
        "date": "2026-06-02",
        "likes": 6,
        "comments": 0,
        "url": "https://blog.naver.com/wings1324/224304113441"
      },
      {
        "title": "이투스247학원 광주수완점 재수 반수 공부자극 확실한 독학관리",
        "blogger": "하랑두랑",
        "date": "2026-06-03",
        "likes": 3,
        "comments": 0,
        "url": "https://blog.naver.com/ever9472/224304969446"
      }
    ],
    "inflowKeywords": [
      {
        "rank": 1,
        "keyword": "광주 이투스 수완 주차",
        "value": "50%"
      },
      {
        "rank": 2,
        "keyword": "광주독학재수학원 썸머스쿨",
        "value": "50%"
      }
    ],
    "exposedKeywords": [
      {
        "rank": 1,
        "keyword": "수완지구 반수",
        "value": "13건"
      },
      {
        "rank": 2,
        "keyword": "이투스247학원 광주수완점",
        "value": "7건"
      }
    ]
  },
  "독학기숙": {
    "totalInfluencers": 4,
    "totalContents": 4,
    "totalViews": 506,
    "averageViews": 127,
    "mobileViews": 338,
    "pcViews": 168,
    "mobileRatio": 67,
    "pcRatio": 33,
    "averageMobileViews": 85,
    "averagePcViews": 42,
    "dailyData": [
      {
        "date": "2026-05-23",
        "day": "토",
        "pc": 35,
        "mobile": 11,
        "total": 46
      },
      {
        "date": "2026-05-24",
        "day": "일",
        "pc": 5,
        "mobile": 12,
        "total": 17
      },
      {
        "date": "2026-05-25",
        "day": "월",
        "pc": 4,
        "mobile": 15,
        "total": 19
      },
      {
        "date": "2026-05-26",
        "day": "화",
        "pc": 4,
        "mobile": 3,
        "total": 7
      },
      {
        "date": "2026-05-27",
        "day": "수",
        "pc": 5,
        "mobile": 8,
        "total": 13
      },
      {
        "date": "2026-05-28",
        "day": "목",
        "pc": 3,
        "mobile": 19,
        "total": 22
      },
      {
        "date": "2026-05-29",
        "day": "금",
        "pc": 1,
        "mobile": 4,
        "total": 5
      },
      {
        "date": "2026-05-30",
        "day": "토",
        "pc": 2,
        "mobile": 7,
        "total": 9
      },
      {
        "date": "2026-05-31",
        "day": "일",
        "pc": 4,
        "mobile": 5,
        "total": 9
      },
      {
        "date": "2026-06-01",
        "day": "월",
        "pc": 3,
        "mobile": 8,
        "total": 11
      },
      {
        "date": "2026-06-02",
        "day": "화",
        "pc": 17,
        "mobile": 14,
        "total": 31
      },
      {
        "date": "2026-06-03",
        "day": "수",
        "pc": 8,
        "mobile": 31,
        "total": 39
      },
      {
        "date": "2026-06-04",
        "day": "목",
        "pc": 6,
        "mobile": 15,
        "total": 21
      },
      {
        "date": "2026-06-05",
        "day": "금",
        "pc": 12,
        "mobile": 29,
        "total": 41
      },
      {
        "date": "2026-06-06",
        "day": "토",
        "pc": 11,
        "mobile": 41,
        "total": 52
      },
      {
        "date": "2026-06-07",
        "day": "일",
        "pc": 19,
        "mobile": 52,
        "total": 71
      },
      {
        "date": "2026-06-08",
        "day": "월",
        "pc": 13,
        "mobile": 29,
        "total": 42
      },
      {
        "date": "2026-06-09",
        "day": "화",
        "pc": 16,
        "mobile": 35,
        "total": 51
      }
    ],
    "contents": [
      {
        "title": "경기 광주 이투스247 독학기숙학원 하루루틴 | 반수성공반 14시간 순공 만드는 독학기숙 시스템",
        "blogger": "호세아1",
        "date": "2026-05-23",
        "likes": 111,
        "comments": 7,
        "url": "https://blog.naver.com/hoshea1/224294340079"
      },
      {
        "title": "이투스247 독학기숙학원 경기광주 직접 방문 후기 | 재수기숙학원 추천",
        "blogger": "세라여왕",
        "date": "2026-06-02",
        "likes": 4,
        "comments": 0,
        "url": "https://blog.naver.com/jwp3214/224303667337?fromRss=true&trackingCode=rss"
      },
      {
        "title": "이투스247 독학기숙학원 경기광주점 독학기숙의 몰입 환경이 인상적이었던 곳",
        "blogger": "하준마마",
        "date": "2026-06-03",
        "likes": 11,
        "comments": 4,
        "url": "https://blog.naver.com/em2868/224304983862?fromRss=true&trackingCode=rss"
      },
      {
        "title": "재수기숙학원 추천 이투스247독학기숙학원 경기광주",
        "blogger": "qhfka4785",
        "date": "2026-06-02",
        "likes": 0,
        "comments": 0,
        "url": "https://blog.naver.com/qhfka4785/224303854745"
      }
    ],
    "inflowKeywords": [
      {
        "rank": 1,
        "keyword": "이투스 247 기숙 광주",
        "value": "19%"
      },
      {
        "rank": 2,
        "keyword": "이투스247독학기숙학원",
        "value": "16%"
      },
      {
        "rank": 3,
        "keyword": "경기 광주 이투스247 독학기숙학원",
        "value": "13%"
      },
      {
        "rank": 4,
        "keyword": "이투스기숙학원",
        "value": "13%"
      },
      {
        "rank": 5,
        "keyword": "경기 광주 이투스247 독학기숙학원 하루루틴",
        "value": "10%"
      },
      {
        "rank": 6,
        "keyword": "광주 이투스 기숙학원",
        "value": "10%"
      },
      {
        "rank": 7,
        "keyword": "광주 이투스 247 기숙학원",
        "value": "6%"
      },
      {
        "rank": 8,
        "keyword": "기숙학원",
        "value": "6%"
      },
      {
        "rank": 9,
        "keyword": "경기광주 재수학원",
        "value": "3%"
      },
      {
        "rank": 10,
        "keyword": "반수기숙학원 추천",
        "value": "3%"
      }
    ],
    "exposedKeywords": []
  },
  "부산교대": {
    "totalInfluencers": 3,
    "totalContents": 3,
    "totalViews": 1167,
    "averageViews": 389,
    "mobileViews": 96,
    "pcViews": 1071,
    "mobileRatio": 8,
    "pcRatio": 92,
    "averageMobileViews": 32,
    "averagePcViews": 357,
    "dailyData": [
      {
        "date": "2026-05-31",
        "day": "일",
        "pc": 1,
        "mobile": 2,
        "total": 3
      },
      {
        "date": "2026-06-01",
        "day": "월",
        "pc": 118,
        "mobile": 6,
        "total": 124
      },
      {
        "date": "2026-06-02",
        "day": "화",
        "pc": 115,
        "mobile": 6,
        "total": 121
      },
      {
        "date": "2026-06-03",
        "day": "수",
        "pc": 133,
        "mobile": 5,
        "total": 138
      },
      {
        "date": "2026-06-04",
        "day": "목",
        "pc": 126,
        "mobile": 16,
        "total": 142
      },
      {
        "date": "2026-06-05",
        "day": "금",
        "pc": 116,
        "mobile": 10,
        "total": 126
      },
      {
        "date": "2026-06-06",
        "day": "토",
        "pc": 120,
        "mobile": 16,
        "total": 136
      },
      {
        "date": "2026-06-07",
        "day": "일",
        "pc": 88,
        "mobile": 8,
        "total": 96
      },
      {
        "date": "2026-06-08",
        "day": "월",
        "pc": 119,
        "mobile": 14,
        "total": 133
      },
      {
        "date": "2026-06-09",
        "day": "화",
        "pc": 135,
        "mobile": 13,
        "total": 148
      }
    ],
    "contents": [
      {
        "title": "이투스247학원 부산교대점 상담 후기｜서면 재수학원 추천",
        "blogger": "366일후",
        "date": "2026-05-31",
        "likes": 2,
        "comments": 0,
        "url": "https://blog.naver.com/wjdqls9796/224301828900?fromRss=true&trackingCode=rss"
      },
      {
        "title": "부산 독학관리학원 이투스247학원 부산교대점 수험생관리 반수 재수학원",
        "blogger": "뿌블",
        "date": "2026-06-01",
        "likes": 18,
        "comments": 5,
        "url": "https://blog.naver.com/jshee45/224302356037?fromRss=true&trackingCode=rss"
      },
      {
        "title": "이투스247학원 부산교대점 2027 반수성공반 직접 다녀온 후기",
        "blogger": "시간블로그",
        "date": "2026-06-03",
        "likes": 0,
        "comments": 2,
        "url": "https://blog.naver.com/thehyuntime/224305136185"
      }
    ],
    "inflowKeywords": [
      {
        "rank": 1,
        "keyword": "부산 반수 학원",
        "value": "11%"
      },
      {
        "rank": 2,
        "keyword": "부산교대 이투스학원",
        "value": "11%"
      },
      {
        "rank": 3,
        "keyword": "부산반수학원",
        "value": "11%"
      },
      {
        "rank": 4,
        "keyword": "부산서면이투스247비용",
        "value": "11%"
      },
      {
        "rank": 5,
        "keyword": "부산재수독학학원",
        "value": "11%"
      },
      {
        "rank": 6,
        "keyword": "이투스247 부산교대",
        "value": "11%"
      },
      {
        "rank": 7,
        "keyword": "반수학원",
        "value": "11%"
      },
      {
        "rank": 8,
        "keyword": "부산 반수학원",
        "value": "11%"
      },
      {
        "rank": 9,
        "keyword": "부산 유명 수능학원",
        "value": "11%"
      }
    ],
    "exposedKeywords": [
      {
        "rank": 1,
        "keyword": "부산교대역 재수",
        "value": "16건"
      }
    ]
  },
  "의정부": {
    "totalInfluencers": 3,
    "totalContents": 3,
    "totalViews": 378,
    "averageViews": 126,
    "mobileViews": 171,
    "pcViews": 207,
    "mobileRatio": 45,
    "pcRatio": 55,
    "averageMobileViews": 57,
    "averagePcViews": 69,
    "dailyData": [
      {
        "date": "2026-05-24",
        "day": "일",
        "pc": 71,
        "mobile": 73,
        "total": 144
      },
      {
        "date": "2026-05-25",
        "day": "월",
        "pc": 4,
        "mobile": 5,
        "total": 9
      },
      {
        "date": "2026-05-26",
        "day": "화",
        "pc": 25,
        "mobile": 8,
        "total": 33
      },
      {
        "date": "2026-05-27",
        "day": "수",
        "pc": 22,
        "mobile": 2,
        "total": 24
      },
      {
        "date": "2026-05-28",
        "day": "목",
        "pc": 16,
        "mobile": 4,
        "total": 20
      },
      {
        "date": "2026-05-29",
        "day": "금",
        "pc": 12,
        "mobile": 11,
        "total": 23
      },
      {
        "date": "2026-05-30",
        "day": "토",
        "pc": 8,
        "mobile": 5,
        "total": 13
      },
      {
        "date": "2026-05-31",
        "day": "일",
        "pc": 3,
        "mobile": 4,
        "total": 7
      },
      {
        "date": "2026-06-01",
        "day": "월",
        "pc": 8,
        "mobile": 3,
        "total": 11
      },
      {
        "date": "2026-06-02",
        "day": "화",
        "pc": 10,
        "mobile": 6,
        "total": 16
      },
      {
        "date": "2026-06-03",
        "day": "수",
        "pc": 4,
        "mobile": 4,
        "total": 8
      },
      {
        "date": "2026-06-04",
        "day": "목",
        "pc": 2,
        "mobile": 8,
        "total": 10
      },
      {
        "date": "2026-06-05",
        "day": "금",
        "pc": 5,
        "mobile": 7,
        "total": 12
      },
      {
        "date": "2026-06-06",
        "day": "토",
        "pc": 2,
        "mobile": 3,
        "total": 5
      },
      {
        "date": "2026-06-07",
        "day": "일",
        "pc": 5,
        "mobile": 16,
        "total": 21
      },
      {
        "date": "2026-06-08",
        "day": "월",
        "pc": 3,
        "mobile": 7,
        "total": 10
      },
      {
        "date": "2026-06-09",
        "day": "화",
        "pc": 7,
        "mobile": 5,
        "total": 12
      }
    ],
    "contents": [
      {
        "title": "이투스247학원 의정부점 의지박약도 하루 14시간 몰입하게 만드는 갓생 공간 투어",
        "blogger": "물땡시루",
        "date": "2026-05-24",
        "likes": 142,
        "comments": 0,
        "url": "https://blog.naver.com/siroo2016/224294999719"
      },
      {
        "title": "의정부 독학재수학원, 공부 분위기부터 다른 이투스247학원 의정부점",
        "blogger": "ilreen",
        "date": "2026-05-26",
        "likes": 0,
        "comments": 8,
        "url": "https://blog.naver.com/e-ryang/224296464621?fromRss=true&trackingCode=rss"
      },
      {
        "title": "이투스 247학원 의정부점 상담 후기 의정부 재수추천 반수학원",
        "blogger": "예남매",
        "date": "2026-06-02",
        "likes": 21,
        "comments": 1,
        "url": "https://blog.naver.com/eunpiri715/224303507482?fromRss=true&trackingCode=rss"
      }
    ],
    "inflowKeywords": [
      {
        "rank": 1,
        "keyword": "의정부 이투스 247",
        "value": "30%"
      },
      {
        "rank": 2,
        "keyword": "이감 어플 접속",
        "value": "10%"
      },
      {
        "rank": 3,
        "keyword": "이투스 247 생활",
        "value": "10%"
      },
      {
        "rank": 4,
        "keyword": "이투스247",
        "value": "10%"
      },
      {
        "rank": 5,
        "keyword": "의정부 독학 재수",
        "value": "10%"
      },
      {
        "rank": 6,
        "keyword": "의정부 이투스247의정부학원",
        "value": "10%"
      },
      {
        "rank": 7,
        "keyword": "이투스경기북부",
        "value": "10%"
      },
      {
        "rank": 8,
        "keyword": "의정부 반수 설명회",
        "value": "10%"
      }
    ],
    "exposedKeywords": []
  },
  "이천기숙": {
    "totalInfluencers": 3,
    "totalContents": 3,
    "totalViews": 152,
    "averageViews": 51,
    "mobileViews": 86,
    "pcViews": 66,
    "mobileRatio": 57,
    "pcRatio": 43,
    "averageMobileViews": 29,
    "averagePcViews": 22,
    "dailyData": [
      {
        "date": "2026-05-28",
        "day": "목",
        "pc": 0,
        "mobile": 2,
        "total": 2
      },
      {
        "date": "2026-05-29",
        "day": "금",
        "pc": 14,
        "mobile": 5,
        "total": 19
      },
      {
        "date": "2026-05-30",
        "day": "토",
        "pc": 6,
        "mobile": 9,
        "total": 15
      },
      {
        "date": "2026-05-31",
        "day": "일",
        "pc": 5,
        "mobile": 11,
        "total": 16
      },
      {
        "date": "2026-06-01",
        "day": "월",
        "pc": 8,
        "mobile": 7,
        "total": 15
      },
      {
        "date": "2026-06-02",
        "day": "화",
        "pc": 14,
        "mobile": 7,
        "total": 21
      },
      {
        "date": "2026-06-03",
        "day": "수",
        "pc": 4,
        "mobile": 9,
        "total": 13
      },
      {
        "date": "2026-06-04",
        "day": "목",
        "pc": 4,
        "mobile": 7,
        "total": 11
      },
      {
        "date": "2026-06-05",
        "day": "금",
        "pc": 5,
        "mobile": 4,
        "total": 9
      },
      {
        "date": "2026-06-06",
        "day": "토",
        "pc": 5,
        "mobile": 7,
        "total": 12
      },
      {
        "date": "2026-06-07",
        "day": "일",
        "pc": 0,
        "mobile": 11,
        "total": 11
      },
      {
        "date": "2026-06-08",
        "day": "월",
        "pc": 1,
        "mobile": 2,
        "total": 3
      },
      {
        "date": "2026-06-09",
        "day": "화",
        "pc": 0,
        "mobile": 5,
        "total": 5
      }
    ],
    "contents": [
      {
        "title": "[이투스247 이천기숙학원] 2027반수 성공반 모집",
        "blogger": "mzeyo11",
        "date": "2026-05-29",
        "likes": 0,
        "comments": 26,
        "url": "https://blog.naver.com/mzeyo/224299765394"
      },
      {
        "title": "반수성공비결 맞춤 솔루션 \"이투스247 이천기숙학원\"",
        "blogger": "쏘니팍",
        "date": "2026-06-02",
        "likes": 39,
        "comments": 50,
        "url": "https://blog.naver.com/dltmf3292/224299875509?fromRss=true&trackingCode=rss"
      },
      {
        "title": "이투스247 이천기숙학원 반수 기숙학원, 자연 속 기숙학원 공부환경이 좋았던 이천 이투스 재수기숙학원",
        "blogger": "또롱2또롱2",
        "date": "2026-05-28",
        "likes": 7,
        "comments": 2,
        "url": "https://blog.naver.com/golden291055/224299201630?fromRss=true&trackingCode=rss"
      }
    ],
    "inflowKeywords": [
      {
        "rank": 1,
        "keyword": "이천247 기숙",
        "value": "38%"
      },
      {
        "rank": 2,
        "keyword": "이투스기숙학원",
        "value": "25%"
      },
      {
        "rank": 3,
        "keyword": "이천이투스기숙",
        "value": "13%"
      },
      {
        "rank": 4,
        "keyword": "이투스 이천 기숙사",
        "value": "13%"
      },
      {
        "rank": 5,
        "keyword": "이투스 이천기숙학원",
        "value": "13%"
      }
    ],
    "exposedKeywords": [
      {
        "rank": 1,
        "keyword": "이천기숙학원",
        "value": "7건"
      },
      {
        "rank": 2,
        "keyword": "이투스247 기숙학원후기",
        "value": "2건"
      },
      {
        "rank": 3,
        "keyword": "이투스247 이천기숙학원",
        "value": "1건"
      }
    ]
  },
  "인천송도": {
    "totalInfluencers": 3,
    "totalContents": 3,
    "totalViews": 939,
    "averageViews": 313,
    "mobileViews": 60,
    "pcViews": 879,
    "mobileRatio": 6,
    "pcRatio": 94,
    "averageMobileViews": 20,
    "averagePcViews": 293,
    "dailyData": [
      {
        "date": "2026-05-28",
        "day": "목",
        "pc": 7,
        "mobile": 7,
        "total": 14
      },
      {
        "date": "2026-05-29",
        "day": "금",
        "pc": 3,
        "mobile": 13,
        "total": 16
      },
      {
        "date": "2026-05-30",
        "day": "토",
        "pc": 0,
        "mobile": 3,
        "total": 3
      },
      {
        "date": "2026-05-31",
        "day": "일",
        "pc": 1,
        "mobile": 2,
        "total": 3
      },
      {
        "date": "2026-06-01",
        "day": "월",
        "pc": 0,
        "mobile": 0,
        "total": 0
      },
      {
        "date": "2026-06-02",
        "day": "화",
        "pc": 0,
        "mobile": 0,
        "total": 0
      },
      {
        "date": "2026-06-03",
        "day": "수",
        "pc": 6,
        "mobile": 12,
        "total": 18
      },
      {
        "date": "2026-06-04",
        "day": "목",
        "pc": 14,
        "mobile": 5,
        "total": 19
      },
      {
        "date": "2026-06-05",
        "day": "금",
        "pc": 178,
        "mobile": 4,
        "total": 182
      },
      {
        "date": "2026-06-06",
        "day": "토",
        "pc": 152,
        "mobile": 5,
        "total": 157
      },
      {
        "date": "2026-06-07",
        "day": "일",
        "pc": 181,
        "mobile": 5,
        "total": 186
      },
      {
        "date": "2026-06-08",
        "day": "월",
        "pc": 169,
        "mobile": 2,
        "total": 171
      },
      {
        "date": "2026-06-09",
        "day": "화",
        "pc": 168,
        "mobile": 2,
        "total": 170
      }
    ],
    "contents": [
      {
        "title": "인천 독학관리 송도재수학원 찾는다면 이투스247학원 인천송도점",
        "blogger": "노다미언니",
        "date": "2026-06-04",
        "likes": 12,
        "comments": 0,
        "url": "https://blog.naver.com/darara5670/224306170526"
      },
      {
        "title": "이투스247학원 인천송도점 송도 독학재수학원 공부루틴 만들기",
        "blogger": "찌니다당",
        "date": "2026-05-28",
        "likes": 0,
        "comments": 7,
        "url": "https://blog.naver.com/jjjjy0_0/224299170976"
      },
      {
        "title": "[인천/송도] 연수구 반수추천 2027 반수성공반 이투스247학원 인천송도점",
        "blogger": "엄슐랭",
        "date": "2026-06-03",
        "likes": 6,
        "comments": 0,
        "url": "https://blog.naver.com/youngjin9610/224304855223"
      }
    ],
    "inflowKeywords": [
      {
        "rank": 1,
        "keyword": "이투스247학원 인천송도점",
        "value": "67%"
      },
      {
        "rank": 2,
        "keyword": "송도 독학재수학원",
        "value": "33%"
      }
    ],
    "exposedKeywords": [
      {
        "rank": 1,
        "keyword": "인천송도 반수",
        "value": "14건"
      },
      {
        "rank": 2,
        "keyword": "이투스247학원 후기",
        "value": "10건"
      }
    ]
  },
  "인하대": {
    "totalInfluencers": 3,
    "totalContents": 3,
    "totalViews": 165,
    "averageViews": 55,
    "mobileViews": 78,
    "pcViews": 87,
    "mobileRatio": 47,
    "pcRatio": 53,
    "averageMobileViews": 26,
    "averagePcViews": 29,
    "dailyData": [
      {
        "date": "2026-05-22",
        "day": "금",
        "pc": 7,
        "mobile": 2,
        "total": 9
      },
      {
        "date": "2026-05-23",
        "day": "토",
        "pc": 0,
        "mobile": 2,
        "total": 2
      },
      {
        "date": "2026-05-24",
        "day": "일",
        "pc": 3,
        "mobile": 0,
        "total": 3
      },
      {
        "date": "2026-05-25",
        "day": "월",
        "pc": 1,
        "mobile": 1,
        "total": 2
      },
      {
        "date": "2026-05-26",
        "day": "화",
        "pc": 1,
        "mobile": 1,
        "total": 2
      },
      {
        "date": "2026-05-27",
        "day": "수",
        "pc": 2,
        "mobile": 1,
        "total": 3
      },
      {
        "date": "2026-05-28",
        "day": "목",
        "pc": 2,
        "mobile": 0,
        "total": 2
      },
      {
        "date": "2026-05-29",
        "day": "금",
        "pc": 0,
        "mobile": 2,
        "total": 2
      },
      {
        "date": "2026-05-30",
        "day": "토",
        "pc": 0,
        "mobile": 1,
        "total": 1
      },
      {
        "date": "2026-05-31",
        "day": "일",
        "pc": 0,
        "mobile": 1,
        "total": 1
      },
      {
        "date": "2026-06-01",
        "day": "월",
        "pc": 10,
        "mobile": 2,
        "total": 12
      },
      {
        "date": "2026-06-02",
        "day": "화",
        "pc": 13,
        "mobile": 10,
        "total": 23
      },
      {
        "date": "2026-06-03",
        "day": "수",
        "pc": 6,
        "mobile": 14,
        "total": 20
      },
      {
        "date": "2026-06-04",
        "day": "목",
        "pc": 14,
        "mobile": 15,
        "total": 29
      },
      {
        "date": "2026-06-05",
        "day": "금",
        "pc": 8,
        "mobile": 5,
        "total": 13
      },
      {
        "date": "2026-06-06",
        "day": "토",
        "pc": 2,
        "mobile": 4,
        "total": 6
      },
      {
        "date": "2026-06-07",
        "day": "일",
        "pc": 7,
        "mobile": 2,
        "total": 9
      },
      {
        "date": "2026-06-08",
        "day": "월",
        "pc": 6,
        "mobile": 8,
        "total": 14
      },
      {
        "date": "2026-06-09",
        "day": "화",
        "pc": 5,
        "mobile": 7,
        "total": 12
      }
    ],
    "contents": [
      {
        "title": "인하대 공부자극 독학재수학원 이투스247학원 인천인하대점 방문후기",
        "blogger": "뚜미니뿌잉",
        "date": "2026-06-01",
        "likes": 2,
        "comments": 1,
        "url": "https://blog.naver.com/le4955/224302440503"
      },
      {
        "title": "이투스247학원 인하대점 미추홀구 독학재수학원으로 추천",
        "blogger": "릴리쥬스",
        "date": "2026-06-02",
        "likes": 6,
        "comments": 0,
        "url": "https://blog.naver.com/silver_o0/224303642285"
      },
      {
        "title": "이투스247학원 인하대점, 재수생루틴 잡기 좋은 인천 독학재수학원",
        "blogger": "진이어스세상",
        "date": "2026-05-22",
        "likes": 14,
        "comments": 4,
        "url": "https://blog.naver.com/jin2usblog/224293711283"
      }
    ],
    "inflowKeywords": [
      {
        "rank": 1,
        "keyword": "갤럭시북4울트라",
        "value": "25%"
      },
      {
        "rank": 2,
        "keyword": "이투스 인강 어때",
        "value": "25%"
      },
      {
        "rank": 3,
        "keyword": "이투스 재수",
        "value": "25%"
      },
      {
        "rank": 4,
        "keyword": "인하대 재수학원",
        "value": "25%"
      }
    ],
    "exposedKeywords": [
      {
        "rank": 1,
        "keyword": "인하대역 재수",
        "value": "25건"
      },
      {
        "rank": 2,
        "keyword": "247공부환경",
        "value": "8건"
      },
      {
        "rank": 3,
        "keyword": "독학재수",
        "value": "3건"
      },
      {
        "rank": 4,
        "keyword": "독학재수학원",
        "value": "2건"
      },
      {
        "rank": 5,
        "keyword": "재수",
        "value": "2건"
      },
      {
        "rank": 6,
        "keyword": "재수학원추천",
        "value": "1건"
      }
    ]
  },
  "진주": {
    "totalInfluencers": 3,
    "totalContents": 3,
    "totalViews": 87,
    "averageViews": 29,
    "mobileViews": 66,
    "pcViews": 21,
    "mobileRatio": 76,
    "pcRatio": 24,
    "averageMobileViews": 22,
    "averagePcViews": 7,
    "dailyData": [
      {
        "date": "2026-05-22",
        "day": "금",
        "pc": 3,
        "mobile": 3,
        "total": 6
      },
      {
        "date": "2026-05-23",
        "day": "토",
        "pc": 0,
        "mobile": 1,
        "total": 1
      },
      {
        "date": "2026-05-24",
        "day": "일",
        "pc": 1,
        "mobile": 2,
        "total": 3
      },
      {
        "date": "2026-05-25",
        "day": "월",
        "pc": 1,
        "mobile": 2,
        "total": 3
      },
      {
        "date": "2026-05-26",
        "day": "화",
        "pc": 6,
        "mobile": 7,
        "total": 13
      },
      {
        "date": "2026-05-27",
        "day": "수",
        "pc": 0,
        "mobile": 3,
        "total": 3
      },
      {
        "date": "2026-05-28",
        "day": "목",
        "pc": 1,
        "mobile": 3,
        "total": 4
      },
      {
        "date": "2026-05-29",
        "day": "금",
        "pc": 1,
        "mobile": 2,
        "total": 3
      },
      {
        "date": "2026-05-30",
        "day": "토",
        "pc": 0,
        "mobile": 2,
        "total": 2
      },
      {
        "date": "2026-05-31",
        "day": "일",
        "pc": 0,
        "mobile": 1,
        "total": 1
      },
      {
        "date": "2026-06-01",
        "day": "월",
        "pc": 2,
        "mobile": 8,
        "total": 10
      },
      {
        "date": "2026-06-02",
        "day": "화",
        "pc": 1,
        "mobile": 1,
        "total": 2
      },
      {
        "date": "2026-06-03",
        "day": "수",
        "pc": 0,
        "mobile": 7,
        "total": 7
      },
      {
        "date": "2026-06-04",
        "day": "목",
        "pc": 0,
        "mobile": 4,
        "total": 4
      },
      {
        "date": "2026-06-05",
        "day": "금",
        "pc": 1,
        "mobile": 6,
        "total": 7
      },
      {
        "date": "2026-06-06",
        "day": "토",
        "pc": 1,
        "mobile": 2,
        "total": 3
      },
      {
        "date": "2026-06-07",
        "day": "일",
        "pc": 0,
        "mobile": 6,
        "total": 6
      },
      {
        "date": "2026-06-08",
        "day": "월",
        "pc": 2,
        "mobile": 4,
        "total": 6
      },
      {
        "date": "2026-06-09",
        "day": "화",
        "pc": 1,
        "mobile": 2,
        "total": 3
      }
    ],
    "contents": [
      {
        "title": "[진주 재수추천]2027반수성공 이투스247학원 진주점 방문후기",
        "blogger": "세서맘",
        "date": "2026-05-22",
        "likes": 0,
        "comments": 0,
        "url": "https://blog.naver.com/ss-mom90/224293615340?fromRss=true&trackingCode=rss"
      },
      {
        "title": "이투스247학원 진주점 방문기, 2027 반수성공반에서 느끼고 온 완벽한 면학 분위기와 관리 시스템!",
        "blogger": "여똥이",
        "date": "2026-05-26",
        "likes": 41,
        "comments": 2,
        "url": "https://blog.naver.com/gemma0125/224296767307"
      },
      {
        "title": "진주재수학원 추천 이투스247학원 진주점 관리형 재수학원",
        "blogger": "술탱크언니",
        "date": "2026-06-02",
        "likes": 5,
        "comments": 0,
        "url": "https://blog.naver.com/gmldo111/224303685456?fromRss=true&trackingCode=rss"
      }
    ],
    "inflowKeywords": [
      {
        "rank": 1,
        "keyword": "진주 이투스",
        "value": "50%"
      },
      {
        "rank": 2,
        "keyword": "진주이투스학원",
        "value": "50%"
      }
    ],
    "exposedKeywords": [
      {
        "rank": 1,
        "keyword": "이투스247학원 진주점",
        "value": "6건"
      },
      {
        "rank": 2,
        "keyword": "이투스247학원 후기",
        "value": "2건"
      }
    ]
  },
  "천안": {
    "totalInfluencers": 3,
    "totalContents": 3,
    "totalViews": 2517,
    "averageViews": 839,
    "mobileViews": 2482,
    "pcViews": 35,
    "mobileRatio": 99,
    "pcRatio": 1,
    "averageMobileViews": 827,
    "averagePcViews": 12,
    "dailyData": [
      {
        "date": "2026-05-29",
        "day": "금",
        "pc": 1,
        "mobile": 6,
        "total": 7
      },
      {
        "date": "2026-05-30",
        "day": "토",
        "pc": 2,
        "mobile": 2,
        "total": 4
      },
      {
        "date": "2026-05-31",
        "day": "일",
        "pc": 3,
        "mobile": 6,
        "total": 9
      },
      {
        "date": "2026-06-01",
        "day": "월",
        "pc": 4,
        "mobile": 3,
        "total": 7
      },
      {
        "date": "2026-06-02",
        "day": "화",
        "pc": 4,
        "mobile": 6,
        "total": 10
      },
      {
        "date": "2026-06-03",
        "day": "수",
        "pc": 1,
        "mobile": 8,
        "total": 9
      },
      {
        "date": "2026-06-04",
        "day": "목",
        "pc": 3,
        "mobile": 14,
        "total": 17
      },
      {
        "date": "2026-06-05",
        "day": "금",
        "pc": 2,
        "mobile": 6,
        "total": 8
      },
      {
        "date": "2026-06-06",
        "day": "토",
        "pc": 1,
        "mobile": 5,
        "total": 6
      },
      {
        "date": "2026-06-07",
        "day": "일",
        "pc": 0,
        "mobile": 6,
        "total": 6
      },
      {
        "date": "2026-06-08",
        "day": "월",
        "pc": 1,
        "mobile": 156,
        "total": 157
      },
      {
        "date": "2026-06-09",
        "day": "화",
        "pc": 13,
        "mobile": 2264,
        "total": 2277
      }
    ],
    "contents": [
      {
        "title": "이투스247학원 천안점, 철저한 독학재수 관리를 품은 천안 재수학원 및 천안 반수추천",
        "blogger": "인물그램",
        "date": "2026-06-01",
        "likes": 1,
        "comments": 0,
        "url": "https://blog.naver.com/blog_time/224303175932"
      },
      {
        "title": "천안 재수학원 찾는다면? 이투스 247학원 천안점 상담 받은 후기",
        "blogger": "리블리하우스",
        "date": "2026-05-29",
        "likes": 42,
        "comments": 1,
        "url": "https://blog.naver.com/ggoda621/224299779334"
      },
      {
        "title": "이투스247학원 천안점, 재수학원추천",
        "blogger": "안수지",
        "date": "2026-06-03",
        "likes": 4,
        "comments": 4,
        "url": "https://blog.naver.com/suzibb/224305158276?fromRss=true&trackingCode=rss"
      }
    ],
    "inflowKeywords": [
      {
        "rank": 1,
        "keyword": "천안독학재수학원",
        "value": "100%"
      }
    ],
    "exposedKeywords": [
      {
        "rank": 1,
        "keyword": "이투스247학원 천안점",
        "value": "6건"
      },
      {
        "rank": 2,
        "keyword": "천안 재수",
        "value": "2건"
      }
    ]
  },
  "하남": {
    "totalInfluencers": 3,
    "totalContents": 3,
    "totalViews": 292,
    "averageViews": 97,
    "mobileViews": 163,
    "pcViews": 129,
    "mobileRatio": 56,
    "pcRatio": 44,
    "averageMobileViews": 54,
    "averagePcViews": 43,
    "dailyData": [
      {
        "date": "2026-05-21",
        "day": "목",
        "pc": 7,
        "mobile": 12,
        "total": 19
      },
      {
        "date": "2026-05-22",
        "day": "금",
        "pc": 1,
        "mobile": 3,
        "total": 4
      },
      {
        "date": "2026-05-23",
        "day": "토",
        "pc": 0,
        "mobile": 4,
        "total": 4
      },
      {
        "date": "2026-05-24",
        "day": "일",
        "pc": 1,
        "mobile": 1,
        "total": 2
      },
      {
        "date": "2026-05-25",
        "day": "월",
        "pc": 1,
        "mobile": 2,
        "total": 3
      },
      {
        "date": "2026-05-26",
        "day": "화",
        "pc": 0,
        "mobile": 0,
        "total": 0
      },
      {
        "date": "2026-05-27",
        "day": "수",
        "pc": 1,
        "mobile": 3,
        "total": 4
      },
      {
        "date": "2026-05-28",
        "day": "목",
        "pc": 26,
        "mobile": 15,
        "total": 41
      },
      {
        "date": "2026-05-29",
        "day": "금",
        "pc": 2,
        "mobile": 3,
        "total": 5
      },
      {
        "date": "2026-05-30",
        "day": "토",
        "pc": 8,
        "mobile": 4,
        "total": 12
      },
      {
        "date": "2026-05-31",
        "day": "일",
        "pc": 5,
        "mobile": 0,
        "total": 5
      },
      {
        "date": "2026-06-01",
        "day": "월",
        "pc": 5,
        "mobile": 5,
        "total": 10
      },
      {
        "date": "2026-06-02",
        "day": "화",
        "pc": 10,
        "mobile": 7,
        "total": 17
      },
      {
        "date": "2026-06-03",
        "day": "수",
        "pc": 7,
        "mobile": 10,
        "total": 17
      },
      {
        "date": "2026-06-04",
        "day": "목",
        "pc": 9,
        "mobile": 14,
        "total": 23
      },
      {
        "date": "2026-06-05",
        "day": "금",
        "pc": 13,
        "mobile": 5,
        "total": 18
      },
      {
        "date": "2026-06-06",
        "day": "토",
        "pc": 3,
        "mobile": 17,
        "total": 20
      },
      {
        "date": "2026-06-07",
        "day": "일",
        "pc": 10,
        "mobile": 29,
        "total": 39
      },
      {
        "date": "2026-06-08",
        "day": "월",
        "pc": 2,
        "mobile": 18,
        "total": 20
      },
      {
        "date": "2026-06-09",
        "day": "화",
        "pc": 18,
        "mobile": 11,
        "total": 29
      }
    ],
    "contents": [
      {
        "title": "독학재수학원 이투스247학원 하남점 추천, 하남 재수 성공의 지름길!",
        "blogger": "하루1133",
        "date": "2026-05-28",
        "likes": 103,
        "comments": 14,
        "url": "https://blog.naver.com/tjrudska82/224298459122?fromRss=true&trackingCode=rss"
      },
      {
        "title": "하남 재수학원 추천, 공부환경이 인상적이었던 이투스247학원 하남점",
        "blogger": "gracejji",
        "date": "2026-06-03",
        "likes": 6,
        "comments": 1,
        "url": "https://blog.naver.com/gracejji/224304993758?fromRss=true&trackingCode=rss"
      },
      {
        "title": "하남 재수 학원 이투스247미사 수능 준비 문제없어",
        "blogger": "지니지니얌2",
        "date": "2026-05-21",
        "likes": 14,
        "comments": 3,
        "url": "https://blog.naver.com/jshj9244/224292319326?fromRss=true&trackingCode=rss"
      }
    ],
    "inflowKeywords": [
      {
        "rank": 1,
        "keyword": "이투스247",
        "value": "29%"
      },
      {
        "rank": 2,
        "keyword": "하남재수학원",
        "value": "14%"
      },
      {
        "rank": 3,
        "keyword": "에코나우",
        "value": "14%"
      },
      {
        "rank": 4,
        "keyword": "오다이바 하루 여행",
        "value": "14%"
      },
      {
        "rank": 5,
        "keyword": "하남 학원 오픈",
        "value": "14%"
      },
      {
        "rank": 6,
        "keyword": "미사 재수독학학원",
        "value": "14%"
      }
    ],
    "exposedKeywords": [
      {
        "rank": 1,
        "keyword": "247공부환경",
        "value": "19건"
      },
      {
        "rank": 2,
        "keyword": "이투스247학원 하남점",
        "value": "1건"
      }
    ]
  }
};
