// Automatically generated by parse-reports.js
window.reportsData = {
  "광주북구": {
    "totalInfluencers": 2,
    "totalContents": 2,
    "totalViews": 362,
    "averageViews": 181,
    "mobileViews": 42,
    "pcViews": 320,
    "mobileRatio": 12,
    "pcRatio": 88,
    "averageMobileViews": 21,
    "averagePcViews": 160,
    "dailyData": [
      {
        "date": "2026-05-29",
        "day": "금",
        "pc": 1,
        "mobile": 0,
        "total": 1
      },
      {
        "date": "2026-05-30",
        "day": "토",
        "pc": 4,
        "mobile": 3,
        "total": 7
      },
      {
        "date": "2026-05-31",
        "day": "일",
        "pc": 0,
        "mobile": 2,
        "total": 2
      },
      {
        "date": "2026-06-01",
        "day": "월",
        "pc": 6,
        "mobile": 5,
        "total": 11
      },
      {
        "date": "2026-06-02",
        "day": "화",
        "pc": 42,
        "mobile": 3,
        "total": 45
      },
      {
        "date": "2026-06-03",
        "day": "수",
        "pc": 17,
        "mobile": 5,
        "total": 22
      },
      {
        "date": "2026-06-04",
        "day": "목",
        "pc": 23,
        "mobile": 2,
        "total": 25
      },
      {
        "date": "2026-06-05",
        "day": "금",
        "pc": 31,
        "mobile": 1,
        "total": 32
      },
      {
        "date": "2026-06-06",
        "day": "토",
        "pc": 24,
        "mobile": 4,
        "total": 28
      },
      {
        "date": "2026-06-07",
        "day": "일",
        "pc": 20,
        "mobile": 6,
        "total": 26
      },
      {
        "date": "2026-06-08",
        "day": "월",
        "pc": 17,
        "mobile": 0,
        "total": 17
      },
      {
        "date": "2026-06-09",
        "day": "화",
        "pc": 25,
        "mobile": 6,
        "total": 31
      },
      {
        "date": "2026-06-10",
        "day": "수",
        "pc": 29,
        "mobile": 0,
        "total": 29
      },
      {
        "date": "2026-06-11",
        "day": "목",
        "pc": 27,
        "mobile": 3,
        "total": 30
      },
      {
        "date": "2026-06-12",
        "day": "금",
        "pc": 18,
        "mobile": 1,
        "total": 19
      },
      {
        "date": "2026-06-13",
        "day": "토",
        "pc": 20,
        "mobile": 1,
        "total": 21
      },
      {
        "date": "2026-06-14",
        "day": "일",
        "pc": 16,
        "mobile": 0,
        "total": 16
      }
    ],
    "contents": [
      {
        "title": "광주 북구 재수 준비한다면? 이투스247학원 광주북구점 광주 반수추천 선택 이유",
        "blogger": "연듀빵듀",
        "date": "2026-06-01",
        "likes": 0,
        "comments": 1,
        "url": "https://blog.naver.com/wannabsoo/224303032487"
      },
      {
        "title": "광주 반수추천 이투스247학원 광주북구점",
        "blogger": "아로미다",
        "date": "2026-05-29",
        "likes": 17,
        "comments": 4,
        "url": "https://blog.naver.com/happy0463/224300507979"
      }
    ],
    "inflowKeywords": [
      {
        "rank": 1,
        "keyword": "광주 북구 재수",
        "value": "33%"
      },
      {
        "rank": 2,
        "keyword": "이투스 247 방",
        "value": "33%"
      },
      {
        "rank": 3,
        "keyword": "운암동 자습학원",
        "value": "33%"
      }
    ],
    "exposedKeywords": [
      {
        "rank": 1,
        "keyword": "운암동 반수",
        "value": "19건"
      },
      {
        "rank": 2,
        "keyword": "이투스247학원 광주북구점",
        "value": "0건"
      }
    ]
  },
  "광주수완": {
    "totalInfluencers": 3,
    "totalContents": 3,
    "totalViews": 192,
    "averageViews": 64,
    "mobileViews": 103,
    "pcViews": 89,
    "mobileRatio": 54,
    "pcRatio": 46,
    "averageMobileViews": 34,
    "averagePcViews": 30,
    "dailyData": [
      {
        "date": "2026-06-02",
        "day": "화",
        "pc": 12,
        "mobile": 8,
        "total": 20
      },
      {
        "date": "2026-06-03",
        "day": "수",
        "pc": 9,
        "mobile": 16,
        "total": 25
      },
      {
        "date": "2026-06-04",
        "day": "목",
        "pc": 8,
        "mobile": 8,
        "total": 16
      },
      {
        "date": "2026-06-05",
        "day": "금",
        "pc": 10,
        "mobile": 5,
        "total": 15
      },
      {
        "date": "2026-06-06",
        "day": "토",
        "pc": 10,
        "mobile": 5,
        "total": 15
      },
      {
        "date": "2026-06-07",
        "day": "일",
        "pc": 7,
        "mobile": 9,
        "total": 16
      },
      {
        "date": "2026-06-08",
        "day": "월",
        "pc": 4,
        "mobile": 8,
        "total": 12
      },
      {
        "date": "2026-06-09",
        "day": "화",
        "pc": 5,
        "mobile": 2,
        "total": 7
      },
      {
        "date": "2026-06-10",
        "day": "수",
        "pc": 5,
        "mobile": 5,
        "total": 10
      },
      {
        "date": "2026-06-11",
        "day": "목",
        "pc": 5,
        "mobile": 8,
        "total": 13
      },
      {
        "date": "2026-06-12",
        "day": "금",
        "pc": 6,
        "mobile": 12,
        "total": 18
      },
      {
        "date": "2026-06-13",
        "day": "토",
        "pc": 4,
        "mobile": 12,
        "total": 16
      },
      {
        "date": "2026-06-14",
        "day": "일",
        "pc": 4,
        "mobile": 5,
        "total": 9
      }
    ],
    "contents": [
      {
        "title": "수완지구 이투스247학원 광주 독학관리 잘 하는 곳",
        "blogger": "yyiyuhyun",
        "date": "2026-06-02",
        "likes": 3,
        "comments": 1,
        "url": "https://blog.naver.com/yyiyuhyun/224303573025"
      },
      {
        "title": "광주 독학관리 반수학원 이투스247학원 광주수완점",
        "blogger": "judy13",
        "date": "2026-06-02",
        "likes": 6,
        "comments": 0,
        "url": "https://blog.naver.com/wings1324/224304113441"
      },
      {
        "title": "이투스247학원 광주수완점 재수 반수 공부자극 확실한 독학관리",
        "blogger": "하랑두랑",
        "date": "2026-06-03",
        "likes": 3,
        "comments": 0,
        "url": "https://blog.naver.com/ever9472/224304969446"
      }
    ],
    "inflowKeywords": [
      {
        "rank": 1,
        "keyword": "광주독학재수학원",
        "value": "33%"
      },
      {
        "rank": 2,
        "keyword": "광주 이투스 수완 주차",
        "value": "33%"
      },
      {
        "rank": 3,
        "keyword": "광주독학재수학원 썸머스쿨",
        "value": "33%"
      }
    ],
    "exposedKeywords": [
      {
        "rank": 1,
        "keyword": "수완지구 반수",
        "value": "13건"
      },
      {
        "rank": 2,
        "keyword": "이투스247학원 광주수완점",
        "value": "7건"
      },
      {
        "rank": 3,
        "keyword": "이투스247학원 후기",
        "value": "0건"
      }
    ]
  },
  "대치": {
    "totalInfluencers": 3,
    "totalContents": 3,
    "totalViews": 144,
    "averageViews": 48,
    "mobileViews": 102,
    "pcViews": 42,
    "mobileRatio": 71,
    "pcRatio": 29,
    "averageMobileViews": 34,
    "averagePcViews": 14,
    "dailyData": [
      {
        "date": "2026-06-02",
        "day": "화",
        "pc": 5,
        "mobile": 6,
        "total": 11
      },
      {
        "date": "2026-06-03",
        "day": "수",
        "pc": 10,
        "mobile": 13,
        "total": 23
      },
      {
        "date": "2026-06-04",
        "day": "목",
        "pc": 11,
        "mobile": 7,
        "total": 18
      },
      {
        "date": "2026-06-05",
        "day": "금",
        "pc": 1,
        "mobile": 4,
        "total": 5
      },
      {
        "date": "2026-06-06",
        "day": "토",
        "pc": 2,
        "mobile": 9,
        "total": 11
      },
      {
        "date": "2026-06-07",
        "day": "일",
        "pc": 0,
        "mobile": 2,
        "total": 2
      },
      {
        "date": "2026-06-08",
        "day": "월",
        "pc": 1,
        "mobile": 5,
        "total": 6
      },
      {
        "date": "2026-06-09",
        "day": "화",
        "pc": 6,
        "mobile": 11,
        "total": 17
      },
      {
        "date": "2026-06-10",
        "day": "수",
        "pc": 3,
        "mobile": 5,
        "total": 8
      },
      {
        "date": "2026-06-11",
        "day": "목",
        "pc": 2,
        "mobile": 11,
        "total": 13
      },
      {
        "date": "2026-06-12",
        "day": "금",
        "pc": 0,
        "mobile": 5,
        "total": 5
      },
      {
        "date": "2026-06-13",
        "day": "토",
        "pc": 0,
        "mobile": 11,
        "total": 11
      },
      {
        "date": "2026-06-14",
        "day": "일",
        "pc": 1,
        "mobile": 13,
        "total": 14
      }
    ],
    "contents": [
      {
        "title": "대치동 반수학원 독학재수 학원 찾는다면 이투스247학원 대치점",
        "blogger": "항항잉",
        "date": "2026-06-02",
        "likes": 4,
        "comments": 1,
        "url": "https://blog.naver.com/poolmoon7/224304040075?fromRss=true&trackingCode=rss"
      },
      {
        "title": "대치동 반수학원 재수관리 시설좋은 자기주도학습관 이투스247학원 대치점",
        "blogger": "TONGNECO",
        "date": "2026-06-03",
        "likes": 10,
        "comments": 1,
        "url": "https://blog.naver.com/be-focus/224304783676?fromRss=true&trackingCode=rss"
      },
      {
        "title": "대치동 반수학원 찾는다면? 이투스247학원 대치점 2027 반수성공반 후기",
        "blogger": "알포트",
        "date": "2026-06-03",
        "likes": 0,
        "comments": 7,
        "url": "https://blog.naver.com/dxlfz/224305084920?fromRss=true&trackingCode=rss"
      }
    ],
    "inflowKeywords": [
      {
        "rank": 1,
        "keyword": "대치동 반수학원",
        "value": "27%"
      },
      {
        "rank": 2,
        "keyword": "이투스247대치 급식",
        "value": "27%"
      },
      {
        "rank": 3,
        "keyword": "대치동 재수학원",
        "value": "9%"
      },
      {
        "rank": 4,
        "keyword": "이투스대치독서실",
        "value": "9%"
      },
      {
        "rank": 5,
        "keyword": "이투스 247 대치 1층 2층",
        "value": "9%"
      },
      {
        "rank": 6,
        "keyword": "이투스247 대치 가격",
        "value": "9%"
      },
      {
        "rank": 7,
        "keyword": "재수 대치 독재학원 추천",
        "value": "9%"
      }
    ],
    "exposedKeywords": [
      {
        "rank": 1,
        "keyword": "이투스247학원 대치점",
        "value": "16건"
      },
      {
        "rank": 2,
        "keyword": "대치동 재수",
        "value": "0건"
      },
      {
        "rank": 3,
        "keyword": "247공부환경",
        "value": "0건"
      }
    ]
  },
  "독학기숙": {
    "totalInfluencers": 4,
    "totalContents": 4,
    "totalViews": 724,
    "averageViews": 181,
    "mobileViews": 505,
    "pcViews": 219,
    "mobileRatio": 70,
    "pcRatio": 30,
    "averageMobileViews": 126,
    "averagePcViews": 55,
    "dailyData": [
      {
        "date": "2026-05-23",
        "day": "토",
        "pc": 35,
        "mobile": 11,
        "total": 46
      },
      {
        "date": "2026-05-24",
        "day": "일",
        "pc": 5,
        "mobile": 12,
        "total": 17
      },
      {
        "date": "2026-05-25",
        "day": "월",
        "pc": 4,
        "mobile": 15,
        "total": 19
      },
      {
        "date": "2026-05-26",
        "day": "화",
        "pc": 4,
        "mobile": 3,
        "total": 7
      },
      {
        "date": "2026-05-27",
        "day": "수",
        "pc": 5,
        "mobile": 8,
        "total": 13
      },
      {
        "date": "2026-05-28",
        "day": "목",
        "pc": 3,
        "mobile": 19,
        "total": 22
      },
      {
        "date": "2026-05-29",
        "day": "금",
        "pc": 1,
        "mobile": 4,
        "total": 5
      },
      {
        "date": "2026-05-30",
        "day": "토",
        "pc": 2,
        "mobile": 7,
        "total": 9
      },
      {
        "date": "2026-05-31",
        "day": "일",
        "pc": 4,
        "mobile": 5,
        "total": 9
      },
      {
        "date": "2026-06-01",
        "day": "월",
        "pc": 3,
        "mobile": 8,
        "total": 11
      },
      {
        "date": "2026-06-02",
        "day": "화",
        "pc": 17,
        "mobile": 14,
        "total": 31
      },
      {
        "date": "2026-06-03",
        "day": "수",
        "pc": 8,
        "mobile": 31,
        "total": 39
      },
      {
        "date": "2026-06-04",
        "day": "목",
        "pc": 6,
        "mobile": 15,
        "total": 21
      },
      {
        "date": "2026-06-05",
        "day": "금",
        "pc": 12,
        "mobile": 29,
        "total": 41
      },
      {
        "date": "2026-06-06",
        "day": "토",
        "pc": 11,
        "mobile": 41,
        "total": 52
      },
      {
        "date": "2026-06-07",
        "day": "일",
        "pc": 19,
        "mobile": 52,
        "total": 71
      },
      {
        "date": "2026-06-08",
        "day": "월",
        "pc": 13,
        "mobile": 29,
        "total": 42
      },
      {
        "date": "2026-06-09",
        "day": "화",
        "pc": 16,
        "mobile": 35,
        "total": 51
      },
      {
        "date": "2026-06-10",
        "day": "수",
        "pc": 12,
        "mobile": 35,
        "total": 47
      },
      {
        "date": "2026-06-11",
        "day": "목",
        "pc": 12,
        "mobile": 35,
        "total": 47
      },
      {
        "date": "2026-06-12",
        "day": "금",
        "pc": 12,
        "mobile": 32,
        "total": 44
      },
      {
        "date": "2026-06-13",
        "day": "토",
        "pc": 8,
        "mobile": 33,
        "total": 41
      },
      {
        "date": "2026-06-14",
        "day": "일",
        "pc": 7,
        "mobile": 32,
        "total": 39
      }
    ],
    "contents": [
      {
        "title": "경기 광주 이투스247 독학기숙학원 하루루틴 | 반수성공반 14시간 순공 만드는 독학기숙 시스템",
        "blogger": "호세아1",
        "date": "2026-05-23",
        "likes": 111,
        "comments": 7,
        "url": "https://blog.naver.com/hoshea1/224294340079"
      },
      {
        "title": "이투스247 독학기숙학원 경기광주 직접 방문 후기 | 재수기숙학원 추천",
        "blogger": "세라여왕",
        "date": "2026-06-02",
        "likes": 4,
        "comments": 0,
        "url": "https://blog.naver.com/jwp3214/224303667337?fromRss=true&trackingCode=rss"
      },
      {
        "title": "이투스247 독학기숙학원 경기광주점 독학기숙의 몰입 환경이 인상적이었던 곳",
        "blogger": "하준마마",
        "date": "2026-06-03",
        "likes": 11,
        "comments": 4,
        "url": "https://blog.naver.com/em2868/224304983862?fromRss=true&trackingCode=rss"
      },
      {
        "title": "재수기숙학원 추천 이투스247독학기숙학원 경기광주",
        "blogger": "qhfka4785",
        "date": "2026-06-02",
        "likes": 0,
        "comments": 0,
        "url": "https://blog.naver.com/qhfka4785/224303854745"
      }
    ],
    "inflowKeywords": [
      {
        "rank": 1,
        "keyword": "이투스 247 기숙 광주",
        "value": "17%"
      },
      {
        "rank": 2,
        "keyword": "이투스247독학기숙학원",
        "value": "14%"
      },
      {
        "rank": 3,
        "keyword": "경기 광주 이투스247 독학기숙학원",
        "value": "11%"
      },
      {
        "rank": 4,
        "keyword": "이투스기숙학원",
        "value": "11%"
      },
      {
        "rank": 5,
        "keyword": "이투스독학기숙",
        "value": "11%"
      },
      {
        "rank": 6,
        "keyword": "경기 광주 이투스247 독학기숙학원 하루루틴",
        "value": "8%"
      },
      {
        "rank": 7,
        "keyword": "광주 이투스 기숙학원",
        "value": "8%"
      },
      {
        "rank": 8,
        "keyword": "이투스 247 독학재수기숙",
        "value": "8%"
      },
      {
        "rank": 9,
        "keyword": "광주 이투스 247 기숙학원",
        "value": "6%"
      },
      {
        "rank": 10,
        "keyword": "기숙학원",
        "value": "6%"
      }
    ],
    "exposedKeywords": [
      {
        "rank": 1,
        "keyword": "광주 독학기숙학원",
        "value": "0건"
      },
      {
        "rank": 2,
        "keyword": "광주기숙학원",
        "value": "0건"
      },
      {
        "rank": 3,
        "keyword": "이투스247 독학기숙학원",
        "value": "0건"
      },
      {
        "rank": 4,
        "keyword": "이투스 247",
        "value": "0건"
      },
      {
        "rank": 5,
        "keyword": "이투스247 기숙학원후기",
        "value": "0건"
      }
    ]
  },
  "부산교대": {
    "totalInfluencers": 3,
    "totalContents": 3,
    "totalViews": 1813,
    "averageViews": 604,
    "mobileViews": 131,
    "pcViews": 1682,
    "mobileRatio": 7,
    "pcRatio": 93,
    "averageMobileViews": 44,
    "averagePcViews": 561,
    "dailyData": [
      {
        "date": "2026-05-31",
        "day": "일",
        "pc": 1,
        "mobile": 2,
        "total": 3
      },
      {
        "date": "2026-06-01",
        "day": "월",
        "pc": 118,
        "mobile": 6,
        "total": 124
      },
      {
        "date": "2026-06-02",
        "day": "화",
        "pc": 115,
        "mobile": 6,
        "total": 121
      },
      {
        "date": "2026-06-03",
        "day": "수",
        "pc": 133,
        "mobile": 5,
        "total": 138
      },
      {
        "date": "2026-06-04",
        "day": "목",
        "pc": 126,
        "mobile": 16,
        "total": 142
      },
      {
        "date": "2026-06-05",
        "day": "금",
        "pc": 116,
        "mobile": 10,
        "total": 126
      },
      {
        "date": "2026-06-06",
        "day": "토",
        "pc": 120,
        "mobile": 16,
        "total": 136
      },
      {
        "date": "2026-06-07",
        "day": "일",
        "pc": 88,
        "mobile": 8,
        "total": 96
      },
      {
        "date": "2026-06-08",
        "day": "월",
        "pc": 119,
        "mobile": 14,
        "total": 133
      },
      {
        "date": "2026-06-09",
        "day": "화",
        "pc": 135,
        "mobile": 13,
        "total": 148
      },
      {
        "date": "2026-06-10",
        "day": "수",
        "pc": 105,
        "mobile": 13,
        "total": 118
      },
      {
        "date": "2026-06-11",
        "day": "목",
        "pc": 107,
        "mobile": 9,
        "total": 116
      },
      {
        "date": "2026-06-12",
        "day": "금",
        "pc": 120,
        "mobile": 4,
        "total": 124
      },
      {
        "date": "2026-06-13",
        "day": "토",
        "pc": 139,
        "mobile": 5,
        "total": 144
      },
      {
        "date": "2026-06-14",
        "day": "일",
        "pc": 140,
        "mobile": 4,
        "total": 144
      }
    ],
    "contents": [
      {
        "title": "이투스247학원 부산교대점 상담 후기｜서면 재수학원 추천",
        "blogger": "366일후",
        "date": "2026-05-31",
        "likes": 2,
        "comments": 0,
        "url": "https://blog.naver.com/wjdqls9796/224301828900?fromRss=true&trackingCode=rss"
      },
      {
        "title": "부산 독학관리학원 이투스247학원 부산교대점 수험생관리 반수 재수학원",
        "blogger": "뿌블",
        "date": "2026-06-01",
        "likes": 18,
        "comments": 5,
        "url": "https://blog.naver.com/jshee45/224302356037?fromRss=true&trackingCode=rss"
      },
      {
        "title": "이투스247학원 부산교대점 2027 반수성공반 직접 다녀온 후기",
        "blogger": "시간블로그",
        "date": "2026-06-03",
        "likes": 0,
        "comments": 2,
        "url": "https://blog.naver.com/thehyuntime/224305136185"
      }
    ],
    "inflowKeywords": [
      {
        "rank": 1,
        "keyword": "부산 반수학원",
        "value": "18%"
      },
      {
        "rank": 2,
        "keyword": "반수학원",
        "value": "9%"
      },
      {
        "rank": 3,
        "keyword": "부산 유명 수능학원",
        "value": "9%"
      },
      {
        "rank": 4,
        "keyword": "이투스247",
        "value": "9%"
      },
      {
        "rank": 5,
        "keyword": "이투스247 부산교대점",
        "value": "9%"
      },
      {
        "rank": 6,
        "keyword": "이투스부산교대",
        "value": "9%"
      },
      {
        "rank": 7,
        "keyword": "부산 관리형 이투스",
        "value": "9%"
      },
      {
        "rank": 8,
        "keyword": "부산 반수 학원",
        "value": "9%"
      },
      {
        "rank": 9,
        "keyword": "부산 재수학원",
        "value": "9%"
      },
      {
        "rank": 10,
        "keyword": "부산교대 이투스학원",
        "value": "9%"
      }
    ],
    "exposedKeywords": [
      {
        "rank": 1,
        "keyword": "부산교대역 재수",
        "value": "16건"
      },
      {
        "rank": 2,
        "keyword": "이투스247학원 부산교대점",
        "value": "0건"
      },
      {
        "rank": 3,
        "keyword": "247공부환경",
        "value": "0건"
      },
      {
        "rank": 4,
        "keyword": "247시스템",
        "value": "0건"
      }
    ]
  },
  "분당정자": {
    "totalInfluencers": 3,
    "totalContents": 3,
    "totalViews": 157,
    "averageViews": 52,
    "mobileViews": 84,
    "pcViews": 73,
    "mobileRatio": 54,
    "pcRatio": 46,
    "averageMobileViews": 28,
    "averagePcViews": 24,
    "dailyData": [
      {
        "date": "2026-05-30",
        "day": "토",
        "pc": 3,
        "mobile": 6,
        "total": 9
      },
      {
        "date": "2026-05-31",
        "day": "일",
        "pc": 3,
        "mobile": 4,
        "total": 7
      },
      {
        "date": "2026-06-01",
        "day": "월",
        "pc": 6,
        "mobile": 8,
        "total": 14
      },
      {
        "date": "2026-06-02",
        "day": "화",
        "pc": 0,
        "mobile": 1,
        "total": 1
      },
      {
        "date": "2026-06-03",
        "day": "수",
        "pc": 11,
        "mobile": 12,
        "total": 23
      },
      {
        "date": "2026-06-04",
        "day": "목",
        "pc": 16,
        "mobile": 9,
        "total": 25
      },
      {
        "date": "2026-06-05",
        "day": "금",
        "pc": 2,
        "mobile": 11,
        "total": 13
      },
      {
        "date": "2026-06-06",
        "day": "토",
        "pc": 3,
        "mobile": 8,
        "total": 11
      },
      {
        "date": "2026-06-07",
        "day": "일",
        "pc": 1,
        "mobile": 7,
        "total": 8
      },
      {
        "date": "2026-06-08",
        "day": "월",
        "pc": 2,
        "mobile": 4,
        "total": 6
      },
      {
        "date": "2026-06-09",
        "day": "화",
        "pc": 8,
        "mobile": 2,
        "total": 10
      },
      {
        "date": "2026-06-10",
        "day": "수",
        "pc": 3,
        "mobile": 1,
        "total": 4
      },
      {
        "date": "2026-06-11",
        "day": "목",
        "pc": 4,
        "mobile": 3,
        "total": 7
      },
      {
        "date": "2026-06-12",
        "day": "금",
        "pc": 2,
        "mobile": 4,
        "total": 6
      },
      {
        "date": "2026-06-13",
        "day": "토",
        "pc": 7,
        "mobile": 1,
        "total": 8
      },
      {
        "date": "2026-06-14",
        "day": "일",
        "pc": 2,
        "mobile": 3,
        "total": 5
      }
    ],
    "contents": [
      {
        "title": "분당 독학재수학원 이투스247학원 분당정자점 공부관리 환경 반수 추천",
        "blogger": "문달쓰",
        "date": "2026-05-30",
        "likes": 0,
        "comments": 5,
        "url": "https://blog.naver.com/mdal2_700/224300732563?fromRss=true&trackingCode=rss"
      },
      {
        "title": "정자역 재수학원 추천 분당 공부관리 잘하는 이투스247학원",
        "blogger": "현성4231",
        "date": "2026-06-03",
        "likes": 0,
        "comments": 1,
        "url": "https://blog.naver.com/hyun_4231/224304784229"
      },
      {
        "title": "이투스247학원 분당정자점 정자역 반수 성공반 후기",
        "blogger": "썸머린",
        "date": "2026-06-03",
        "likes": 0,
        "comments": 0,
        "url": "https://blog.naver.com/rvd_romi/224304965239"
      }
    ],
    "inflowKeywords": [
      {
        "rank": 1,
        "keyword": "이투스247수원정자",
        "value": "13%"
      },
      {
        "rank": 2,
        "keyword": "정자동 공부할만한",
        "value": "13%"
      },
      {
        "rank": 3,
        "keyword": "관리형 독서실 이투스 정자",
        "value": "13%"
      },
      {
        "rank": 4,
        "keyword": "분당 독학재수",
        "value": "13%"
      },
      {
        "rank": 5,
        "keyword": "이투스 247 독재 가격",
        "value": "13%"
      },
      {
        "rank": 6,
        "keyword": "이투스 247 독학재수학원 가격",
        "value": "13%"
      },
      {
        "rank": 7,
        "keyword": "이투스 한수",
        "value": "13%"
      },
      {
        "rank": 8,
        "keyword": "이투스분당점",
        "value": "13%"
      }
    ],
    "exposedKeywords": [
      {
        "rank": 1,
        "keyword": "정자역 반수",
        "value": "25건"
      },
      {
        "rank": 2,
        "keyword": "이투스247학원 분당정자점",
        "value": "0건"
      },
      {
        "rank": 3,
        "keyword": "이투스247학원 후기",
        "value": "0건"
      }
    ]
  },
  "서울광진": {
    "totalInfluencers": 3,
    "totalContents": 3,
    "totalViews": 146,
    "averageViews": 49,
    "mobileViews": 64,
    "pcViews": 82,
    "mobileRatio": 44,
    "pcRatio": 56,
    "averageMobileViews": 21,
    "averagePcViews": 27,
    "dailyData": [
      {
        "date": "2026-06-01",
        "day": "월",
        "pc": 4,
        "mobile": 1,
        "total": 5
      },
      {
        "date": "2026-06-02",
        "day": "화",
        "pc": 1,
        "mobile": 1,
        "total": 2
      },
      {
        "date": "2026-06-03",
        "day": "수",
        "pc": 9,
        "mobile": 5,
        "total": 14
      },
      {
        "date": "2026-06-04",
        "day": "목",
        "pc": 14,
        "mobile": 7,
        "total": 21
      },
      {
        "date": "2026-06-05",
        "day": "금",
        "pc": 8,
        "mobile": 2,
        "total": 10
      },
      {
        "date": "2026-06-06",
        "day": "토",
        "pc": 5,
        "mobile": 6,
        "total": 11
      },
      {
        "date": "2026-06-07",
        "day": "일",
        "pc": 6,
        "mobile": 5,
        "total": 11
      },
      {
        "date": "2026-06-08",
        "day": "월",
        "pc": 4,
        "mobile": 4,
        "total": 8
      },
      {
        "date": "2026-06-09",
        "day": "화",
        "pc": 6,
        "mobile": 4,
        "total": 10
      },
      {
        "date": "2026-06-10",
        "day": "수",
        "pc": 5,
        "mobile": 17,
        "total": 22
      },
      {
        "date": "2026-06-11",
        "day": "목",
        "pc": 3,
        "mobile": 3,
        "total": 6
      },
      {
        "date": "2026-06-12",
        "day": "금",
        "pc": 8,
        "mobile": 3,
        "total": 11
      },
      {
        "date": "2026-06-13",
        "day": "토",
        "pc": 7,
        "mobile": 4,
        "total": 11
      },
      {
        "date": "2026-06-14",
        "day": "일",
        "pc": 2,
        "mobile": 2,
        "total": 4
      }
    ],
    "contents": [
      {
        "title": "건대 재수학원 찾는다면 이투스247학원 서울광진점 주목",
        "blogger": "고추밭에사는여왕",
        "date": "2026-06-03",
        "likes": 33,
        "comments": 0,
        "url": "https://blog.naver.com/0331ska/224305047126?fromRss=true&trackingCode=rss"
      },
      {
        "title": "건대 재수학원 이투스247학원 서울광진점 공부자극 스터디플래너",
        "blogger": "기동이",
        "date": "2026-06-01",
        "likes": 23,
        "comments": 1,
        "url": "https://blog.naver.com/lkd8659/224302848736"
      },
      {
        "title": "서울 반수추천 건대 재수학원 이투스 247학원 서울광진점 2027 반수성공반",
        "blogger": "사쁜",
        "date": "2026-06-03",
        "likes": 0,
        "comments": 1,
        "url": "https://blog.naver.com/sabbeun/224305144268"
      }
    ],
    "inflowKeywords": [
      {
        "rank": 1,
        "keyword": "이투스247 광진",
        "value": "100%"
      }
    ],
    "exposedKeywords": [
      {
        "rank": 1,
        "keyword": "247공부환경",
        "value": "8건"
      },
      {
        "rank": 2,
        "keyword": "이투스247학원 광진점",
        "value": "6건"
      },
      {
        "rank": 3,
        "keyword": "광진구 재수",
        "value": "5건"
      }
    ]
  },
  "수원시청": {
    "totalInfluencers": 3,
    "totalContents": 3,
    "totalViews": 180,
    "averageViews": 60,
    "mobileViews": 141,
    "pcViews": 39,
    "mobileRatio": 78,
    "pcRatio": 22,
    "averageMobileViews": 47,
    "averagePcViews": 13,
    "dailyData": [
      {
        "date": "2026-05-29",
        "day": "금",
        "pc": 3,
        "mobile": 10,
        "total": 13
      },
      {
        "date": "2026-05-30",
        "day": "토",
        "pc": 2,
        "mobile": 4,
        "total": 6
      },
      {
        "date": "2026-05-31",
        "day": "일",
        "pc": 0,
        "mobile": 6,
        "total": 6
      },
      {
        "date": "2026-06-01",
        "day": "월",
        "pc": 1,
        "mobile": 1,
        "total": 2
      },
      {
        "date": "2026-06-02",
        "day": "화",
        "pc": 1,
        "mobile": 4,
        "total": 5
      },
      {
        "date": "2026-06-03",
        "day": "수",
        "pc": 5,
        "mobile": 11,
        "total": 16
      },
      {
        "date": "2026-06-04",
        "day": "목",
        "pc": 3,
        "mobile": 6,
        "total": 9
      },
      {
        "date": "2026-06-05",
        "day": "금",
        "pc": 6,
        "mobile": 15,
        "total": 21
      },
      {
        "date": "2026-06-06",
        "day": "토",
        "pc": 1,
        "mobile": 9,
        "total": 10
      },
      {
        "date": "2026-06-07",
        "day": "일",
        "pc": 3,
        "mobile": 17,
        "total": 20
      },
      {
        "date": "2026-06-08",
        "day": "월",
        "pc": 1,
        "mobile": 9,
        "total": 10
      },
      {
        "date": "2026-06-09",
        "day": "화",
        "pc": 6,
        "mobile": 5,
        "total": 11
      },
      {
        "date": "2026-06-10",
        "day": "수",
        "pc": 3,
        "mobile": 8,
        "total": 11
      },
      {
        "date": "2026-06-11",
        "day": "목",
        "pc": 3,
        "mobile": 11,
        "total": 14
      },
      {
        "date": "2026-06-12",
        "day": "금",
        "pc": 1,
        "mobile": 13,
        "total": 14
      },
      {
        "date": "2026-06-13",
        "day": "토",
        "pc": 0,
        "mobile": 5,
        "total": 5
      },
      {
        "date": "2026-06-14",
        "day": "일",
        "pc": 0,
        "mobile": 7,
        "total": 7
      }
    ],
    "contents": [
      {
        "title": "독학재수학원 이투스247학원 수원시청점 가격 후기",
        "blogger": "hapsong",
        "date": "2026-06-03",
        "likes": 0,
        "comments": 0,
        "url": "https://blog.naver.com/dakong0921/224304314828?fromRss=true&trackingCode=rss"
      },
      {
        "title": "수원 재수추천 반수학원 이투스247학원 수원시청점",
        "blogger": "헤이쥬86",
        "date": "2026-05-29",
        "likes": 3,
        "comments": 0,
        "url": "https://blog.naver.com/eunjuyaaa/224299529609?fromRss=true&trackingCode=rss"
      },
      {
        "title": "이투스247학원 수원시청점 재수학원추천 이유 직접 확인한 후기",
        "blogger": "엘리샤0402",
        "date": "2026-06-03",
        "likes": 32,
        "comments": 4,
        "url": "https://blog.naver.com/techno1213/224305063500"
      }
    ],
    "inflowKeywords": [
      {
        "rank": 1,
        "keyword": "수원시청 이투스 247",
        "value": "18%"
      },
      {
        "rank": 2,
        "keyword": "이투스247",
        "value": "18%"
      },
      {
        "rank": 3,
        "keyword": "이투스 247 수원시청 가격",
        "value": "18%"
      },
      {
        "rank": 4,
        "keyword": "반수학원 수원",
        "value": "9%"
      },
      {
        "rank": 5,
        "keyword": "수원 반수학원",
        "value": "9%"
      },
      {
        "rank": 6,
        "keyword": "수원 재수생 독서실",
        "value": "9%"
      },
      {
        "rank": 7,
        "keyword": "이투스 247 독학재수",
        "value": "9%"
      },
      {
        "rank": 8,
        "keyword": "이투스247 학원비",
        "value": "9%"
      }
    ],
    "exposedKeywords": [
      {
        "rank": 1,
        "keyword": "수원시청역 재수",
        "value": "12건"
      },
      {
        "rank": 2,
        "keyword": "247공부환경",
        "value": "11건"
      },
      {
        "rank": 3,
        "keyword": "247시스템",
        "value": "1건"
      },
      {
        "rank": 4,
        "keyword": "이투스247학원 수원시청점",
        "value": "0건"
      },
      {
        "rank": 5,
        "keyword": "재수학원추천",
        "value": "0건"
      }
    ]
  },
  "안산": {
    "totalInfluencers": 3,
    "totalContents": 3,
    "totalViews": 96,
    "averageViews": 32,
    "mobileViews": 70,
    "pcViews": 26,
    "mobileRatio": 73,
    "pcRatio": 27,
    "averageMobileViews": 23,
    "averagePcViews": 9,
    "dailyData": [
      {
        "date": "2026-05-29",
        "day": "금",
        "pc": 7,
        "mobile": 0,
        "total": 7
      },
      {
        "date": "2026-05-30",
        "day": "토",
        "pc": 1,
        "mobile": 6,
        "total": 7
      },
      {
        "date": "2026-05-31",
        "day": "일",
        "pc": 0,
        "mobile": 3,
        "total": 3
      },
      {
        "date": "2026-06-01",
        "day": "월",
        "pc": 3,
        "mobile": 2,
        "total": 5
      },
      {
        "date": "2026-06-02",
        "day": "화",
        "pc": 0,
        "mobile": 0,
        "total": 0
      },
      {
        "date": "2026-06-03",
        "day": "수",
        "pc": 0,
        "mobile": 2,
        "total": 2
      },
      {
        "date": "2026-06-04",
        "day": "목",
        "pc": 2,
        "mobile": 10,
        "total": 12
      },
      {
        "date": "2026-06-05",
        "day": "금",
        "pc": 1,
        "mobile": 3,
        "total": 4
      },
      {
        "date": "2026-06-06",
        "day": "토",
        "pc": 1,
        "mobile": 8,
        "total": 9
      },
      {
        "date": "2026-06-07",
        "day": "일",
        "pc": 1,
        "mobile": 5,
        "total": 6
      },
      {
        "date": "2026-06-08",
        "day": "월",
        "pc": 7,
        "mobile": 5,
        "total": 12
      },
      {
        "date": "2026-06-09",
        "day": "화",
        "pc": 1,
        "mobile": 3,
        "total": 4
      },
      {
        "date": "2026-06-10",
        "day": "수",
        "pc": 2,
        "mobile": 3,
        "total": 5
      },
      {
        "date": "2026-06-11",
        "day": "목",
        "pc": 0,
        "mobile": 3,
        "total": 3
      },
      {
        "date": "2026-06-12",
        "day": "금",
        "pc": 0,
        "mobile": 4,
        "total": 4
      },
      {
        "date": "2026-06-13",
        "day": "토",
        "pc": 0,
        "mobile": 5,
        "total": 5
      },
      {
        "date": "2026-06-14",
        "day": "일",
        "pc": 0,
        "mobile": 8,
        "total": 8
      }
    ],
    "contents": [
      {
        "title": "안산 재수 이투스247학원 안산점 2027 반수성공반 독학재수학원 추천",
        "blogger": "헤이쭈링",
        "date": "2026-05-29",
        "likes": 0,
        "comments": 1,
        "url": "https://blog.naver.com/hhjjoo_/224300402378"
      },
      {
        "title": "안산 독학학원 : 이투스247학원 안산점 공부하기 좋은 환경이네요.",
        "blogger": "톨토라",
        "date": "2026-06-08",
        "likes": 7,
        "comments": 0,
        "url": "https://blog.naver.com/yhj88/224309603265"
      },
      {
        "title": "이투스247학원 안산점 재수관리, 중앙역 재수학원 안산 반수추천(안산 독학학원)",
        "blogger": "제이경이",
        "date": "2026-06-03",
        "likes": 4,
        "comments": 0,
        "url": "https://blog.naver.com/doli177/224304816107?fromRss=true&trackingCode=rss"
      }
    ],
    "inflowKeywords": [
      {
        "rank": 1,
        "keyword": "안산 독학재수",
        "value": "25%"
      },
      {
        "rank": 2,
        "keyword": "안산 재수학원",
        "value": "25%"
      },
      {
        "rank": 3,
        "keyword": "안산재수",
        "value": "25%"
      },
      {
        "rank": 4,
        "keyword": "이투스 독학재수 안산 급식",
        "value": "25%"
      }
    ],
    "exposedKeywords": [
      {
        "rank": 1,
        "keyword": "247공부환경",
        "value": "6건"
      },
      {
        "rank": 2,
        "keyword": "안산 재수",
        "value": "4건"
      },
      {
        "rank": 3,
        "keyword": "재수학원추천",
        "value": "4건"
      },
      {
        "rank": 4,
        "keyword": "이투스247학원 안산점",
        "value": "3건"
      }
    ]
  },
  "의정부": {
    "totalInfluencers": 3,
    "totalContents": 3,
    "totalViews": 435,
    "averageViews": 145,
    "mobileViews": 209,
    "pcViews": 226,
    "mobileRatio": 48,
    "pcRatio": 52,
    "averageMobileViews": 70,
    "averagePcViews": 75,
    "dailyData": [
      {
        "date": "2026-05-24",
        "day": "일",
        "pc": 71,
        "mobile": 73,
        "total": 144
      },
      {
        "date": "2026-05-25",
        "day": "월",
        "pc": 4,
        "mobile": 5,
        "total": 9
      },
      {
        "date": "2026-05-26",
        "day": "화",
        "pc": 25,
        "mobile": 8,
        "total": 33
      },
      {
        "date": "2026-05-27",
        "day": "수",
        "pc": 22,
        "mobile": 2,
        "total": 24
      },
      {
        "date": "2026-05-28",
        "day": "목",
        "pc": 16,
        "mobile": 4,
        "total": 20
      },
      {
        "date": "2026-05-29",
        "day": "금",
        "pc": 12,
        "mobile": 11,
        "total": 23
      },
      {
        "date": "2026-05-30",
        "day": "토",
        "pc": 8,
        "mobile": 5,
        "total": 13
      },
      {
        "date": "2026-05-31",
        "day": "일",
        "pc": 3,
        "mobile": 4,
        "total": 7
      },
      {
        "date": "2026-06-01",
        "day": "월",
        "pc": 8,
        "mobile": 3,
        "total": 11
      },
      {
        "date": "2026-06-02",
        "day": "화",
        "pc": 10,
        "mobile": 6,
        "total": 16
      },
      {
        "date": "2026-06-03",
        "day": "수",
        "pc": 4,
        "mobile": 4,
        "total": 8
      },
      {
        "date": "2026-06-04",
        "day": "목",
        "pc": 2,
        "mobile": 8,
        "total": 10
      },
      {
        "date": "2026-06-05",
        "day": "금",
        "pc": 5,
        "mobile": 7,
        "total": 12
      },
      {
        "date": "2026-06-06",
        "day": "토",
        "pc": 2,
        "mobile": 3,
        "total": 5
      },
      {
        "date": "2026-06-07",
        "day": "일",
        "pc": 5,
        "mobile": 16,
        "total": 21
      },
      {
        "date": "2026-06-08",
        "day": "월",
        "pc": 3,
        "mobile": 7,
        "total": 10
      },
      {
        "date": "2026-06-09",
        "day": "화",
        "pc": 7,
        "mobile": 5,
        "total": 12
      },
      {
        "date": "2026-06-10",
        "day": "수",
        "pc": 12,
        "mobile": 9,
        "total": 21
      },
      {
        "date": "2026-06-11",
        "day": "목",
        "pc": 6,
        "mobile": 8,
        "total": 14
      },
      {
        "date": "2026-06-12",
        "day": "금",
        "pc": 1,
        "mobile": 6,
        "total": 7
      },
      {
        "date": "2026-06-13",
        "day": "토",
        "pc": 0,
        "mobile": 6,
        "total": 6
      },
      {
        "date": "2026-06-14",
        "day": "일",
        "pc": 0,
        "mobile": 9,
        "total": 9
      }
    ],
    "contents": [
      {
        "title": "이투스247학원 의정부점 의지박약도 하루 14시간 몰입하게 만드는 갓생 공간 투어",
        "blogger": "물땡시루",
        "date": "2026-05-24",
        "likes": 142,
        "comments": 0,
        "url": "https://blog.naver.com/siroo2016/224294999719"
      },
      {
        "title": "의정부 독학재수학원, 공부 분위기부터 다른 이투스247학원 의정부점",
        "blogger": "ilreen",
        "date": "2026-05-26",
        "likes": 0,
        "comments": 8,
        "url": "https://blog.naver.com/e-ryang/224296464621?fromRss=true&trackingCode=rss"
      },
      {
        "title": "이투스 247학원 의정부점 상담 후기 의정부 재수추천 반수학원",
        "blogger": "예남매",
        "date": "2026-06-02",
        "likes": 21,
        "comments": 1,
        "url": "https://blog.naver.com/eunpiri715/224303507482?fromRss=true&trackingCode=rss"
      }
    ],
    "inflowKeywords": [
      {
        "rank": 1,
        "keyword": "의정부 이투스 247",
        "value": "21%"
      },
      {
        "rank": 2,
        "keyword": "이투스의정부점 후기",
        "value": "14%"
      },
      {
        "rank": 3,
        "keyword": "의정부 관리형 독서실 추천",
        "value": "14%"
      },
      {
        "rank": 4,
        "keyword": "의정부 반수 설명회",
        "value": "7%"
      },
      {
        "rank": 5,
        "keyword": "의정부 독학 재수",
        "value": "7%"
      },
      {
        "rank": 6,
        "keyword": "의정부 이투스247의정부학원",
        "value": "7%"
      },
      {
        "rank": 7,
        "keyword": "이투스경기북부",
        "value": "7%"
      },
      {
        "rank": 8,
        "keyword": "관리형 독서실 의정부",
        "value": "7%"
      },
      {
        "rank": 9,
        "keyword": "의정부 관리형 독서실 후기",
        "value": "7%"
      },
      {
        "rank": 10,
        "keyword": "이감 어플 접속",
        "value": "7%"
      }
    ],
    "exposedKeywords": [
      {
        "rank": 1,
        "keyword": "이투스247학원 의정부점",
        "value": "0건"
      },
      {
        "rank": 2,
        "keyword": "의정부 재수",
        "value": "0건"
      },
      {
        "rank": 3,
        "keyword": "247시스템",
        "value": "0건"
      }
    ]
  },
  "이천기숙": {
    "totalInfluencers": 3,
    "totalContents": 3,
    "totalViews": 180,
    "averageViews": 60,
    "mobileViews": 103,
    "pcViews": 77,
    "mobileRatio": 57,
    "pcRatio": 43,
    "averageMobileViews": 34,
    "averagePcViews": 26,
    "dailyData": [
      {
        "date": "2026-05-28",
        "day": "목",
        "pc": 0,
        "mobile": 2,
        "total": 2
      },
      {
        "date": "2026-05-29",
        "day": "금",
        "pc": 14,
        "mobile": 5,
        "total": 19
      },
      {
        "date": "2026-05-30",
        "day": "토",
        "pc": 6,
        "mobile": 9,
        "total": 15
      },
      {
        "date": "2026-05-31",
        "day": "일",
        "pc": 5,
        "mobile": 11,
        "total": 16
      },
      {
        "date": "2026-06-01",
        "day": "월",
        "pc": 8,
        "mobile": 7,
        "total": 15
      },
      {
        "date": "2026-06-02",
        "day": "화",
        "pc": 14,
        "mobile": 7,
        "total": 21
      },
      {
        "date": "2026-06-03",
        "day": "수",
        "pc": 4,
        "mobile": 9,
        "total": 13
      },
      {
        "date": "2026-06-04",
        "day": "목",
        "pc": 4,
        "mobile": 7,
        "total": 11
      },
      {
        "date": "2026-06-05",
        "day": "금",
        "pc": 5,
        "mobile": 4,
        "total": 9
      },
      {
        "date": "2026-06-06",
        "day": "토",
        "pc": 5,
        "mobile": 7,
        "total": 12
      },
      {
        "date": "2026-06-07",
        "day": "일",
        "pc": 0,
        "mobile": 11,
        "total": 11
      },
      {
        "date": "2026-06-08",
        "day": "월",
        "pc": 1,
        "mobile": 2,
        "total": 3
      },
      {
        "date": "2026-06-09",
        "day": "화",
        "pc": 0,
        "mobile": 5,
        "total": 5
      },
      {
        "date": "2026-06-10",
        "day": "수",
        "pc": 2,
        "mobile": 6,
        "total": 8
      },
      {
        "date": "2026-06-11",
        "day": "목",
        "pc": 6,
        "mobile": 0,
        "total": 6
      },
      {
        "date": "2026-06-12",
        "day": "금",
        "pc": 0,
        "mobile": 3,
        "total": 3
      },
      {
        "date": "2026-06-13",
        "day": "토",
        "pc": 2,
        "mobile": 7,
        "total": 9
      },
      {
        "date": "2026-06-14",
        "day": "일",
        "pc": 1,
        "mobile": 1,
        "total": 2
      }
    ],
    "contents": [
      {
        "title": "[이투스247 이천기숙학원] 2027반수 성공반 모집",
        "blogger": "mzeyo11",
        "date": "2026-05-29",
        "likes": 0,
        "comments": 26,
        "url": "https://blog.naver.com/mzeyo/224299765394"
      },
      {
        "title": "반수성공비결 맞춤 솔루션 \"이투스247 이천기숙학원\"",
        "blogger": "쏘니팍",
        "date": "2026-06-02",
        "likes": 39,
        "comments": 50,
        "url": "https://blog.naver.com/dltmf3292/224299875509?fromRss=true&trackingCode=rss"
      },
      {
        "title": "이투스247 이천기숙학원 반수 기숙학원, 자연 속 기숙학원 공부환경이 좋았던 이천 이투스 재수기숙학원",
        "blogger": "또롱2또롱2",
        "date": "2026-05-28",
        "likes": 7,
        "comments": 2,
        "url": "https://blog.naver.com/golden291055/224299201630?fromRss=true&trackingCode=rss"
      }
    ],
    "inflowKeywords": [
      {
        "rank": 1,
        "keyword": "이천247 기숙",
        "value": "25%"
      },
      {
        "rank": 2,
        "keyword": "이투스기숙학원",
        "value": "17%"
      },
      {
        "rank": 3,
        "keyword": "수원 반수종합반",
        "value": "8%"
      },
      {
        "rank": 4,
        "keyword": "이천이투스기숙",
        "value": "8%"
      },
      {
        "rank": 5,
        "keyword": "이투스 247 이천 후기",
        "value": "8%"
      },
      {
        "rank": 6,
        "keyword": "이투스 이천 기숙사",
        "value": "8%"
      },
      {
        "rank": 7,
        "keyword": "이투스 이천 독학",
        "value": "8%"
      },
      {
        "rank": 8,
        "keyword": "이투스 이천기숙학원",
        "value": "8%"
      },
      {
        "rank": 9,
        "keyword": "이투스 247 이천",
        "value": "8%"
      }
    ],
    "exposedKeywords": [
      {
        "rank": 1,
        "keyword": "이천기숙학원",
        "value": "7건"
      },
      {
        "rank": 2,
        "keyword": "이투스247 기숙학원후기",
        "value": "2건"
      },
      {
        "rank": 3,
        "keyword": "이투스247 이천기숙학원",
        "value": "1건"
      }
    ]
  },
  "인천송도": {
    "totalInfluencers": 3,
    "totalContents": 3,
    "totalViews": 1828,
    "averageViews": 609,
    "mobileViews": 84,
    "pcViews": 1744,
    "mobileRatio": 5,
    "pcRatio": 95,
    "averageMobileViews": 28,
    "averagePcViews": 581,
    "dailyData": [
      {
        "date": "2026-05-28",
        "day": "목",
        "pc": 7,
        "mobile": 7,
        "total": 14
      },
      {
        "date": "2026-05-29",
        "day": "금",
        "pc": 3,
        "mobile": 13,
        "total": 16
      },
      {
        "date": "2026-05-30",
        "day": "토",
        "pc": 0,
        "mobile": 3,
        "total": 3
      },
      {
        "date": "2026-05-31",
        "day": "일",
        "pc": 1,
        "mobile": 2,
        "total": 3
      },
      {
        "date": "2026-06-01",
        "day": "월",
        "pc": 0,
        "mobile": 0,
        "total": 0
      },
      {
        "date": "2026-06-02",
        "day": "화",
        "pc": 0,
        "mobile": 0,
        "total": 0
      },
      {
        "date": "2026-06-03",
        "day": "수",
        "pc": 6,
        "mobile": 12,
        "total": 18
      },
      {
        "date": "2026-06-04",
        "day": "목",
        "pc": 14,
        "mobile": 5,
        "total": 19
      },
      {
        "date": "2026-06-05",
        "day": "금",
        "pc": 178,
        "mobile": 4,
        "total": 182
      },
      {
        "date": "2026-06-06",
        "day": "토",
        "pc": 152,
        "mobile": 5,
        "total": 157
      },
      {
        "date": "2026-06-07",
        "day": "일",
        "pc": 181,
        "mobile": 5,
        "total": 186
      },
      {
        "date": "2026-06-08",
        "day": "월",
        "pc": 169,
        "mobile": 2,
        "total": 171
      },
      {
        "date": "2026-06-09",
        "day": "화",
        "pc": 168,
        "mobile": 2,
        "total": 170
      },
      {
        "date": "2026-06-10",
        "day": "수",
        "pc": 172,
        "mobile": 7,
        "total": 179
      },
      {
        "date": "2026-06-11",
        "day": "목",
        "pc": 189,
        "mobile": 6,
        "total": 195
      },
      {
        "date": "2026-06-12",
        "day": "금",
        "pc": 167,
        "mobile": 3,
        "total": 170
      },
      {
        "date": "2026-06-13",
        "day": "토",
        "pc": 162,
        "mobile": 6,
        "total": 168
      },
      {
        "date": "2026-06-14",
        "day": "일",
        "pc": 175,
        "mobile": 2,
        "total": 177
      }
    ],
    "contents": [
      {
        "title": "인천 독학관리 송도재수학원 찾는다면 이투스247학원 인천송도점",
        "blogger": "노다미언니",
        "date": "2026-06-04",
        "likes": 12,
        "comments": 0,
        "url": "https://blog.naver.com/darara5670/224306170526"
      },
      {
        "title": "[인천/송도] 연수구 반수추천 2027 반수성공반 이투스247학원 인천송도점",
        "blogger": "엄슐랭",
        "date": "2026-06-03",
        "likes": 6,
        "comments": 0,
        "url": "https://blog.naver.com/youngjin9610/224304855223"
      },
      {
        "title": "이투스247학원 인천송도점 송도 독학재수학원 공부루틴 만들기",
        "blogger": "찌니다당",
        "date": "2026-05-28",
        "likes": 0,
        "comments": 7,
        "url": "https://blog.naver.com/jjjjy0_0/224299170976"
      }
    ],
    "inflowKeywords": [
      {
        "rank": 1,
        "keyword": "이투스247학원 인천송도점",
        "value": "33%"
      },
      {
        "rank": 2,
        "keyword": "송도재수학원",
        "value": "17%"
      },
      {
        "rank": 3,
        "keyword": "인천 재수학원",
        "value": "17%"
      },
      {
        "rank": 4,
        "keyword": "인천송도독학재수학원",
        "value": "17%"
      },
      {
        "rank": 5,
        "keyword": "송도 독학재수학원",
        "value": "17%"
      }
    ],
    "exposedKeywords": [
      {
        "rank": 1,
        "keyword": "인천송도 반수",
        "value": "14건"
      },
      {
        "rank": 2,
        "keyword": "이투스247학원 후기",
        "value": "10건"
      },
      {
        "rank": 3,
        "keyword": "이투스247학원 인천송도점",
        "value": "0건"
      }
    ]
  },
  "인하대": {
    "totalInfluencers": 3,
    "totalContents": 3,
    "totalViews": 229,
    "averageViews": 76,
    "mobileViews": 115,
    "pcViews": 114,
    "mobileRatio": 50,
    "pcRatio": 50,
    "averageMobileViews": 38,
    "averagePcViews": 38,
    "dailyData": [
      {
        "date": "2026-05-22",
        "day": "금",
        "pc": 7,
        "mobile": 2,
        "total": 9
      },
      {
        "date": "2026-05-23",
        "day": "토",
        "pc": 0,
        "mobile": 2,
        "total": 2
      },
      {
        "date": "2026-05-24",
        "day": "일",
        "pc": 3,
        "mobile": 0,
        "total": 3
      },
      {
        "date": "2026-05-25",
        "day": "월",
        "pc": 1,
        "mobile": 1,
        "total": 2
      },
      {
        "date": "2026-05-26",
        "day": "화",
        "pc": 1,
        "mobile": 1,
        "total": 2
      },
      {
        "date": "2026-05-27",
        "day": "수",
        "pc": 2,
        "mobile": 1,
        "total": 3
      },
      {
        "date": "2026-05-28",
        "day": "목",
        "pc": 2,
        "mobile": 0,
        "total": 2
      },
      {
        "date": "2026-05-29",
        "day": "금",
        "pc": 0,
        "mobile": 2,
        "total": 2
      },
      {
        "date": "2026-05-30",
        "day": "토",
        "pc": 0,
        "mobile": 1,
        "total": 1
      },
      {
        "date": "2026-05-31",
        "day": "일",
        "pc": 0,
        "mobile": 1,
        "total": 1
      },
      {
        "date": "2026-06-01",
        "day": "월",
        "pc": 10,
        "mobile": 2,
        "total": 12
      },
      {
        "date": "2026-06-02",
        "day": "화",
        "pc": 13,
        "mobile": 10,
        "total": 23
      },
      {
        "date": "2026-06-03",
        "day": "수",
        "pc": 6,
        "mobile": 14,
        "total": 20
      },
      {
        "date": "2026-06-04",
        "day": "목",
        "pc": 14,
        "mobile": 15,
        "total": 29
      },
      {
        "date": "2026-06-05",
        "day": "금",
        "pc": 8,
        "mobile": 5,
        "total": 13
      },
      {
        "date": "2026-06-06",
        "day": "토",
        "pc": 2,
        "mobile": 4,
        "total": 6
      },
      {
        "date": "2026-06-07",
        "day": "일",
        "pc": 7,
        "mobile": 2,
        "total": 9
      },
      {
        "date": "2026-06-08",
        "day": "월",
        "pc": 6,
        "mobile": 8,
        "total": 14
      },
      {
        "date": "2026-06-09",
        "day": "화",
        "pc": 5,
        "mobile": 7,
        "total": 12
      },
      {
        "date": "2026-06-10",
        "day": "수",
        "pc": 5,
        "mobile": 8,
        "total": 13
      },
      {
        "date": "2026-06-11",
        "day": "목",
        "pc": 5,
        "mobile": 6,
        "total": 11
      },
      {
        "date": "2026-06-12",
        "day": "금",
        "pc": 6,
        "mobile": 10,
        "total": 16
      },
      {
        "date": "2026-06-13",
        "day": "토",
        "pc": 5,
        "mobile": 5,
        "total": 10
      },
      {
        "date": "2026-06-14",
        "day": "일",
        "pc": 6,
        "mobile": 8,
        "total": 14
      }
    ],
    "contents": [
      {
        "title": "이투스247학원 인하대점 미추홀구 독학재수학원으로 추천",
        "blogger": "릴리쥬스",
        "date": "2026-06-02",
        "likes": 6,
        "comments": 0,
        "url": "https://blog.naver.com/silver_o0/224303642285"
      },
      {
        "title": "인하대 공부자극 독학재수학원 이투스247학원 인천인하대점 방문후기",
        "blogger": "뚜미니뿌잉",
        "date": "2026-06-01",
        "likes": 2,
        "comments": 1,
        "url": "https://blog.naver.com/le4955/224302440503"
      },
      {
        "title": "이투스247학원 인하대점, 재수생루틴 잡기 좋은 인천 독학재수학원",
        "blogger": "진이어스세상",
        "date": "2026-05-22",
        "likes": 14,
        "comments": 4,
        "url": "https://blog.naver.com/jin2usblog/224293711283"
      }
    ],
    "inflowKeywords": [
      {
        "rank": 1,
        "keyword": "갤럭시북4울트라",
        "value": "25%"
      },
      {
        "rank": 2,
        "keyword": "이투스 인강 어때",
        "value": "25%"
      },
      {
        "rank": 3,
        "keyword": "이투스 재수",
        "value": "25%"
      },
      {
        "rank": 4,
        "keyword": "인하대 재수학원",
        "value": "25%"
      }
    ],
    "exposedKeywords": [
      {
        "rank": 1,
        "keyword": "인하대역 재수",
        "value": "25건"
      },
      {
        "rank": 2,
        "keyword": "247공부환경",
        "value": "8건"
      },
      {
        "rank": 3,
        "keyword": "독학재수",
        "value": "3건"
      },
      {
        "rank": 4,
        "keyword": "독학재수학원",
        "value": "2건"
      },
      {
        "rank": 5,
        "keyword": "재수",
        "value": "2건"
      },
      {
        "rank": 6,
        "keyword": "재수학원추천",
        "value": "1건"
      },
      {
        "rank": 7,
        "keyword": "이투스247학원 인하대점",
        "value": "0건"
      },
      {
        "rank": 8,
        "keyword": "247시스템",
        "value": "0건"
      }
    ]
  },
  "일산동구": {
    "totalInfluencers": 3,
    "totalContents": 3,
    "totalViews": 152,
    "averageViews": 51,
    "mobileViews": 117,
    "pcViews": 35,
    "mobileRatio": 77,
    "pcRatio": 23,
    "averageMobileViews": 39,
    "averagePcViews": 12,
    "dailyData": [
      {
        "date": "2026-05-30",
        "day": "토",
        "pc": 6,
        "mobile": 13,
        "total": 19
      },
      {
        "date": "2026-05-31",
        "day": "일",
        "pc": 0,
        "mobile": 1,
        "total": 1
      },
      {
        "date": "2026-06-01",
        "day": "월",
        "pc": 0,
        "mobile": 1,
        "total": 1
      },
      {
        "date": "2026-06-02",
        "day": "화",
        "pc": 0,
        "mobile": 2,
        "total": 2
      },
      {
        "date": "2026-06-03",
        "day": "수",
        "pc": 8,
        "mobile": 25,
        "total": 33
      },
      {
        "date": "2026-06-04",
        "day": "목",
        "pc": 7,
        "mobile": 27,
        "total": 34
      },
      {
        "date": "2026-06-05",
        "day": "금",
        "pc": 1,
        "mobile": 3,
        "total": 4
      },
      {
        "date": "2026-06-06",
        "day": "토",
        "pc": 3,
        "mobile": 6,
        "total": 9
      },
      {
        "date": "2026-06-07",
        "day": "일",
        "pc": 1,
        "mobile": 8,
        "total": 9
      },
      {
        "date": "2026-06-08",
        "day": "월",
        "pc": 1,
        "mobile": 5,
        "total": 6
      },
      {
        "date": "2026-06-09",
        "day": "화",
        "pc": 6,
        "mobile": 4,
        "total": 10
      },
      {
        "date": "2026-06-10",
        "day": "수",
        "pc": 1,
        "mobile": 7,
        "total": 8
      },
      {
        "date": "2026-06-11",
        "day": "목",
        "pc": 0,
        "mobile": 4,
        "total": 4
      },
      {
        "date": "2026-06-12",
        "day": "금",
        "pc": 1,
        "mobile": 4,
        "total": 5
      },
      {
        "date": "2026-06-13",
        "day": "토",
        "pc": 0,
        "mobile": 2,
        "total": 2
      },
      {
        "date": "2026-06-14",
        "day": "일",
        "pc": 0,
        "mobile": 5,
        "total": 5
      }
    ],
    "contents": [
      {
        "title": "일산 독학재수 학원 이투스247학원 일산동구점 시설 및 학습관리 후기",
        "blogger": "ariluxe",
        "date": "2026-06-03",
        "likes": 0,
        "comments": 9,
        "url": "https://blog.naver.com/haeriut1156_/224305065178?fromRss=true&trackingCode=rss"
      },
      {
        "title": "이투스247학원 일산동구점 백마학원가 독학재수학원",
        "blogger": "ddo_log",
        "date": "2026-06-03",
        "likes": 10,
        "comments": 1,
        "url": "https://blog.naver.com/alswl3002/224304625521"
      },
      {
        "title": "백마학원가 재수, 서울대 4명 합격으로 증명된 이투스247학원 일산동구점 솔직 후기",
        "blogger": "stephania",
        "date": "2026-05-30",
        "likes": 27,
        "comments": 8,
        "url": "https://blog.naver.com/kwon411/224300742621"
      }
    ],
    "inflowKeywords": [
      {
        "rank": 1,
        "keyword": "일산독학재수학원",
        "value": "31%"
      },
      {
        "rank": 2,
        "keyword": "일산 독학재수학원",
        "value": "23%"
      },
      {
        "rank": 3,
        "keyword": "이투스247일산",
        "value": "15%"
      },
      {
        "rank": 4,
        "keyword": "백마 학원가 학원 운영",
        "value": "8%"
      },
      {
        "rank": 5,
        "keyword": "백마학원가 이투스수학",
        "value": "8%"
      },
      {
        "rank": 6,
        "keyword": "일산 백마 독학재수",
        "value": "8%"
      },
      {
        "rank": 7,
        "keyword": "학원 휴대폰 벽 보관",
        "value": "8%"
      }
    ],
    "exposedKeywords": [
      {
        "rank": 1,
        "keyword": "백마역 재수",
        "value": "22건"
      },
      {
        "rank": 2,
        "keyword": "247공부환경",
        "value": "10건"
      },
      {
        "rank": 3,
        "keyword": "이투스247학원 일산동구점",
        "value": "6건"
      },
      {
        "rank": 4,
        "keyword": "247시스템",
        "value": "0건"
      }
    ]
  },
  "일산서구": {
    "totalInfluencers": 3,
    "totalContents": 3,
    "totalViews": 337,
    "averageViews": 112,
    "mobileViews": 165,
    "pcViews": 172,
    "mobileRatio": 49,
    "pcRatio": 51,
    "averageMobileViews": 55,
    "averagePcViews": 57,
    "dailyData": [
      {
        "date": "2026-06-03",
        "day": "수",
        "pc": 15,
        "mobile": 10,
        "total": 25
      },
      {
        "date": "2026-06-04",
        "day": "목",
        "pc": 96,
        "mobile": 93,
        "total": 189
      },
      {
        "date": "2026-06-05",
        "day": "금",
        "pc": 10,
        "mobile": 13,
        "total": 23
      },
      {
        "date": "2026-06-06",
        "day": "토",
        "pc": 11,
        "mobile": 7,
        "total": 18
      },
      {
        "date": "2026-06-07",
        "day": "일",
        "pc": 4,
        "mobile": 6,
        "total": 10
      },
      {
        "date": "2026-06-08",
        "day": "월",
        "pc": 6,
        "mobile": 6,
        "total": 12
      },
      {
        "date": "2026-06-09",
        "day": "화",
        "pc": 7,
        "mobile": 6,
        "total": 13
      },
      {
        "date": "2026-06-10",
        "day": "수",
        "pc": 7,
        "mobile": 2,
        "total": 9
      },
      {
        "date": "2026-06-11",
        "day": "목",
        "pc": 1,
        "mobile": 11,
        "total": 12
      },
      {
        "date": "2026-06-12",
        "day": "금",
        "pc": 3,
        "mobile": 4,
        "total": 7
      },
      {
        "date": "2026-06-13",
        "day": "토",
        "pc": 5,
        "mobile": 2,
        "total": 7
      },
      {
        "date": "2026-06-14",
        "day": "일",
        "pc": 7,
        "mobile": 5,
        "total": 12
      }
    ],
    "contents": [
      {
        "title": "일산서구 재수학원 찾는다면? 관리형 독서실 시스템 갖춘 이투스247학원 일산서구점 후기",
        "blogger": "오달하",
        "date": "2026-06-03",
        "likes": 164,
        "comments": 3,
        "url": "https://blog.naver.com/ljyhello/224304867054"
      },
      {
        "title": "2027 반수성공반 준비 이투스247학원 일산서구점",
        "blogger": "애니돌",
        "date": "2026-06-03",
        "likes": 22,
        "comments": 0,
        "url": "https://blog.naver.com/skyloves90/224304989851"
      },
      {
        "title": "이투스247학원 일산서구점 | 일산서구 반수 및 고양시 독학재수 성공을 위한 일산 공부관리 (feat. 화정 재수학원 고민 끝)",
        "blogger": "푹삶은토마토",
        "date": "2026-06-03",
        "likes": 4,
        "comments": 1,
        "url": "https://blog.naver.com/ozozfit/224305092014?fromRss=true&trackingCode=rss"
      }
    ],
    "inflowKeywords": [
      {
        "rank": 1,
        "keyword": "일산 기숙학원",
        "value": "17%"
      },
      {
        "rank": 2,
        "keyword": "일산독학재수학원",
        "value": "17%"
      },
      {
        "rank": 3,
        "keyword": "031-907-0247",
        "value": "8%"
      },
      {
        "rank": 4,
        "keyword": "이투스247일산",
        "value": "8%"
      },
      {
        "rank": 5,
        "keyword": "후곡 재수독학학원",
        "value": "8%"
      },
      {
        "rank": 6,
        "keyword": "화정 맛집",
        "value": "8%"
      },
      {
        "rank": 7,
        "keyword": "고등학생 관리형독서실",
        "value": "8%"
      },
      {
        "rank": 8,
        "keyword": "관리형 독서실 일산",
        "value": "8%"
      },
      {
        "rank": 9,
        "keyword": "이투스 설명회 후기",
        "value": "8%"
      },
      {
        "rank": 10,
        "keyword": "이투스247 주엽점",
        "value": "8%"
      }
    ],
    "exposedKeywords": [
      {
        "rank": 1,
        "keyword": "247공부환경",
        "value": "7건"
      },
      {
        "rank": 2,
        "keyword": "주엽역 재수",
        "value": "5건"
      },
      {
        "rank": 3,
        "keyword": "이투스247학원 일산서구점",
        "value": "0건"
      },
      {
        "rank": 4,
        "keyword": "247시스템",
        "value": "0건"
      }
    ]
  },
  "진주": {
    "totalInfluencers": 3,
    "totalContents": 3,
    "totalViews": 101,
    "averageViews": 34,
    "mobileViews": 74,
    "pcViews": 27,
    "mobileRatio": 73,
    "pcRatio": 27,
    "averageMobileViews": 25,
    "averagePcViews": 9,
    "dailyData": [
      {
        "date": "2026-05-22",
        "day": "금",
        "pc": 3,
        "mobile": 3,
        "total": 6
      },
      {
        "date": "2026-05-23",
        "day": "토",
        "pc": 0,
        "mobile": 1,
        "total": 1
      },
      {
        "date": "2026-05-24",
        "day": "일",
        "pc": 1,
        "mobile": 2,
        "total": 3
      },
      {
        "date": "2026-05-25",
        "day": "월",
        "pc": 1,
        "mobile": 2,
        "total": 3
      },
      {
        "date": "2026-05-26",
        "day": "화",
        "pc": 6,
        "mobile": 7,
        "total": 13
      },
      {
        "date": "2026-05-27",
        "day": "수",
        "pc": 0,
        "mobile": 3,
        "total": 3
      },
      {
        "date": "2026-05-28",
        "day": "목",
        "pc": 1,
        "mobile": 3,
        "total": 4
      },
      {
        "date": "2026-05-29",
        "day": "금",
        "pc": 1,
        "mobile": 2,
        "total": 3
      },
      {
        "date": "2026-05-30",
        "day": "토",
        "pc": 0,
        "mobile": 2,
        "total": 2
      },
      {
        "date": "2026-05-31",
        "day": "일",
        "pc": 0,
        "mobile": 1,
        "total": 1
      },
      {
        "date": "2026-06-01",
        "day": "월",
        "pc": 2,
        "mobile": 8,
        "total": 10
      },
      {
        "date": "2026-06-02",
        "day": "화",
        "pc": 1,
        "mobile": 1,
        "total": 2
      },
      {
        "date": "2026-06-03",
        "day": "수",
        "pc": 0,
        "mobile": 7,
        "total": 7
      },
      {
        "date": "2026-06-04",
        "day": "목",
        "pc": 0,
        "mobile": 4,
        "total": 4
      },
      {
        "date": "2026-06-05",
        "day": "금",
        "pc": 1,
        "mobile": 6,
        "total": 7
      },
      {
        "date": "2026-06-06",
        "day": "토",
        "pc": 1,
        "mobile": 2,
        "total": 3
      },
      {
        "date": "2026-06-07",
        "day": "일",
        "pc": 0,
        "mobile": 6,
        "total": 6
      },
      {
        "date": "2026-06-08",
        "day": "월",
        "pc": 2,
        "mobile": 4,
        "total": 6
      },
      {
        "date": "2026-06-09",
        "day": "화",
        "pc": 1,
        "mobile": 2,
        "total": 3
      },
      {
        "date": "2026-06-10",
        "day": "수",
        "pc": 1,
        "mobile": 2,
        "total": 3
      },
      {
        "date": "2026-06-11",
        "day": "목",
        "pc": 3,
        "mobile": 3,
        "total": 6
      },
      {
        "date": "2026-06-12",
        "day": "금",
        "pc": 1,
        "mobile": 2,
        "total": 3
      },
      {
        "date": "2026-06-13",
        "day": "토",
        "pc": 1,
        "mobile": 0,
        "total": 1
      },
      {
        "date": "2026-06-14",
        "day": "일",
        "pc": 0,
        "mobile": 1,
        "total": 1
      }
    ],
    "contents": [
      {
        "title": "[진주 재수추천]2027반수성공 이투스247학원 진주점 방문후기",
        "blogger": "세서맘",
        "date": "2026-05-22",
        "likes": 0,
        "comments": 0,
        "url": "https://blog.naver.com/ss-mom90/224293615340?fromRss=true&trackingCode=rss"
      },
      {
        "title": "이투스247학원 진주점 방문기, 2027 반수성공반에서 느끼고 온 완벽한 면학 분위기와 관리 시스템!",
        "blogger": "여똥이",
        "date": "2026-05-26",
        "likes": 41,
        "comments": 2,
        "url": "https://blog.naver.com/gemma0125/224296767307"
      },
      {
        "title": "진주재수학원 추천 이투스247학원 진주점 관리형 재수학원",
        "blogger": "술탱크언니",
        "date": "2026-06-02",
        "likes": 5,
        "comments": 0,
        "url": "https://blog.naver.com/gmldo111/224303685456?fromRss=true&trackingCode=rss"
      }
    ],
    "inflowKeywords": [
      {
        "rank": 1,
        "keyword": "LMTI LMAT 이투스",
        "value": "25%"
      },
      {
        "rank": 2,
        "keyword": "진주이투스학원",
        "value": "25%"
      },
      {
        "rank": 3,
        "keyword": "재수학원 도시락",
        "value": "25%"
      },
      {
        "rank": 4,
        "keyword": "진주 이투스",
        "value": "25%"
      }
    ],
    "exposedKeywords": [
      {
        "rank": 1,
        "keyword": "이투스247학원 진주점",
        "value": "6건"
      },
      {
        "rank": 2,
        "keyword": "이투스247학원 후기",
        "value": "2건"
      }
    ]
  },
  "천안": {
    "totalInfluencers": 3,
    "totalContents": 3,
    "totalViews": 2556,
    "averageViews": 852,
    "mobileViews": 2518,
    "pcViews": 38,
    "mobileRatio": 99,
    "pcRatio": 1,
    "averageMobileViews": 839,
    "averagePcViews": 13,
    "dailyData": [
      {
        "date": "2026-05-29",
        "day": "금",
        "pc": 1,
        "mobile": 6,
        "total": 7
      },
      {
        "date": "2026-05-30",
        "day": "토",
        "pc": 2,
        "mobile": 2,
        "total": 4
      },
      {
        "date": "2026-05-31",
        "day": "일",
        "pc": 3,
        "mobile": 6,
        "total": 9
      },
      {
        "date": "2026-06-01",
        "day": "월",
        "pc": 4,
        "mobile": 3,
        "total": 7
      },
      {
        "date": "2026-06-02",
        "day": "화",
        "pc": 4,
        "mobile": 6,
        "total": 10
      },
      {
        "date": "2026-06-03",
        "day": "수",
        "pc": 1,
        "mobile": 8,
        "total": 9
      },
      {
        "date": "2026-06-04",
        "day": "목",
        "pc": 3,
        "mobile": 14,
        "total": 17
      },
      {
        "date": "2026-06-05",
        "day": "금",
        "pc": 2,
        "mobile": 6,
        "total": 8
      },
      {
        "date": "2026-06-06",
        "day": "토",
        "pc": 1,
        "mobile": 5,
        "total": 6
      },
      {
        "date": "2026-06-07",
        "day": "일",
        "pc": 0,
        "mobile": 6,
        "total": 6
      },
      {
        "date": "2026-06-08",
        "day": "월",
        "pc": 1,
        "mobile": 156,
        "total": 157
      },
      {
        "date": "2026-06-09",
        "day": "화",
        "pc": 13,
        "mobile": 2264,
        "total": 2277
      },
      {
        "date": "2026-06-10",
        "day": "수",
        "pc": 1,
        "mobile": 17,
        "total": 18
      },
      {
        "date": "2026-06-11",
        "day": "목",
        "pc": 1,
        "mobile": 8,
        "total": 9
      },
      {
        "date": "2026-06-12",
        "day": "금",
        "pc": 1,
        "mobile": 5,
        "total": 6
      },
      {
        "date": "2026-06-13",
        "day": "토",
        "pc": 0,
        "mobile": 2,
        "total": 2
      },
      {
        "date": "2026-06-14",
        "day": "일",
        "pc": 0,
        "mobile": 4,
        "total": 4
      }
    ],
    "contents": [
      {
        "title": "이투스247학원 천안점, 철저한 독학재수 관리를 품은 천안 재수학원 및 천안 반수추천",
        "blogger": "인물그램",
        "date": "2026-06-01",
        "likes": 1,
        "comments": 0,
        "url": "https://blog.naver.com/blog_time/224303175932"
      },
      {
        "title": "천안 재수학원 찾는다면? 이투스 247학원 천안점 상담 받은 후기",
        "blogger": "리블리하우스",
        "date": "2026-05-29",
        "likes": 42,
        "comments": 1,
        "url": "https://blog.naver.com/ggoda621/224299779334"
      },
      {
        "title": "이투스247학원 천안점, 재수학원추천",
        "blogger": "안수지",
        "date": "2026-06-03",
        "likes": 4,
        "comments": 4,
        "url": "https://blog.naver.com/suzibb/224305158276?fromRss=true&trackingCode=rss"
      }
    ],
    "inflowKeywords": [
      {
        "rank": 1,
        "keyword": "천안독학재수학원",
        "value": "33%"
      },
      {
        "rank": 2,
        "keyword": "천안 재수학원",
        "value": "33%"
      },
      {
        "rank": 3,
        "keyword": "천안재수학원",
        "value": "33%"
      }
    ],
    "exposedKeywords": [
      {
        "rank": 1,
        "keyword": "이투스247학원 천안점",
        "value": "6건"
      },
      {
        "rank": 2,
        "keyword": "천안 재수",
        "value": "2건"
      }
    ]
  },
  "춘천": {
    "totalInfluencers": 3,
    "totalContents": 3,
    "totalViews": 394,
    "averageViews": 131,
    "mobileViews": 276,
    "pcViews": 118,
    "mobileRatio": 70,
    "pcRatio": 30,
    "averageMobileViews": 92,
    "averagePcViews": 39,
    "dailyData": [
      {
        "date": "2026-05-23",
        "day": "토",
        "pc": 4,
        "mobile": 6,
        "total": 10
      },
      {
        "date": "2026-05-24",
        "day": "일",
        "pc": 1,
        "mobile": 11,
        "total": 12
      },
      {
        "date": "2026-05-25",
        "day": "월",
        "pc": 0,
        "mobile": 5,
        "total": 5
      },
      {
        "date": "2026-05-26",
        "day": "화",
        "pc": 2,
        "mobile": 1,
        "total": 3
      },
      {
        "date": "2026-05-27",
        "day": "수",
        "pc": 7,
        "mobile": 9,
        "total": 16
      },
      {
        "date": "2026-05-28",
        "day": "목",
        "pc": 10,
        "mobile": 20,
        "total": 30
      },
      {
        "date": "2026-05-29",
        "day": "금",
        "pc": 12,
        "mobile": 22,
        "total": 34
      },
      {
        "date": "2026-05-30",
        "day": "토",
        "pc": 5,
        "mobile": 17,
        "total": 22
      },
      {
        "date": "2026-05-31",
        "day": "일",
        "pc": 14,
        "mobile": 15,
        "total": 29
      },
      {
        "date": "2026-06-01",
        "day": "월",
        "pc": 5,
        "mobile": 9,
        "total": 14
      },
      {
        "date": "2026-06-02",
        "day": "화",
        "pc": 4,
        "mobile": 11,
        "total": 15
      },
      {
        "date": "2026-06-03",
        "day": "수",
        "pc": 2,
        "mobile": 9,
        "total": 11
      },
      {
        "date": "2026-06-04",
        "day": "목",
        "pc": 1,
        "mobile": 9,
        "total": 10
      },
      {
        "date": "2026-06-05",
        "day": "금",
        "pc": 3,
        "mobile": 12,
        "total": 15
      },
      {
        "date": "2026-06-06",
        "day": "토",
        "pc": 1,
        "mobile": 15,
        "total": 16
      },
      {
        "date": "2026-06-07",
        "day": "일",
        "pc": 8,
        "mobile": 10,
        "total": 18
      },
      {
        "date": "2026-06-08",
        "day": "월",
        "pc": 1,
        "mobile": 14,
        "total": 15
      },
      {
        "date": "2026-06-09",
        "day": "화",
        "pc": 15,
        "mobile": 22,
        "total": 37
      },
      {
        "date": "2026-06-10",
        "day": "수",
        "pc": 9,
        "mobile": 10,
        "total": 19
      },
      {
        "date": "2026-06-11",
        "day": "목",
        "pc": 3,
        "mobile": 7,
        "total": 10
      },
      {
        "date": "2026-06-12",
        "day": "금",
        "pc": 4,
        "mobile": 9,
        "total": 13
      },
      {
        "date": "2026-06-13",
        "day": "토",
        "pc": 2,
        "mobile": 11,
        "total": 13
      },
      {
        "date": "2026-06-14",
        "day": "일",
        "pc": 5,
        "mobile": 22,
        "total": 27
      }
    ],
    "contents": [
      {
        "title": "춘천 공부습관 잡아주는 이투스247학원 춘천점 상담후기",
        "blogger": "아트프롬비니",
        "date": "2026-05-27",
        "likes": 5,
        "comments": 4,
        "url": "https://blog.naver.com/praybin/224297920420"
      },
      {
        "title": "[이투스247학원 춘천점]강원 독학재수 성공 비결! 춘천 반수관리부터 공부습관까지 해결하는 춘천 재수추천 솔직 후기",
        "blogger": "춘천춘식이",
        "date": "2026-05-28",
        "likes": 24,
        "comments": 4,
        "url": "https://blog.naver.com/kmh8104/224298631843?fromRss=true&trackingCode=rss"
      },
      {
        "title": "춘천 반수관리 재수학원 이투스247학원 춘천점 추천",
        "blogger": "태롱둥이",
        "date": "2026-05-23",
        "likes": 6,
        "comments": 2,
        "url": "https://blog.naver.com/taein0208/224294289955?fromRss=true&trackingCode=rss"
      }
    ],
    "inflowKeywords": [
      {
        "rank": 1,
        "keyword": "독학재수학원",
        "value": "25%"
      },
      {
        "rank": 2,
        "keyword": "춘천 1:1 재수학원",
        "value": "25%"
      },
      {
        "rank": 3,
        "keyword": "춘천 독학 독서실",
        "value": "25%"
      },
      {
        "rank": 4,
        "keyword": "춘천재수학원",
        "value": "25%"
      }
    ],
    "exposedKeywords": [
      {
        "rank": 1,
        "keyword": "247시스템",
        "value": "1건"
      },
      {
        "rank": 2,
        "keyword": "반수",
        "value": "1건"
      },
      {
        "rank": 3,
        "keyword": "이투스247학원 춘천점",
        "value": "0건"
      },
      {
        "rank": 4,
        "keyword": "춘천 재수",
        "value": "0건"
      },
      {
        "rank": 5,
        "keyword": "247공부환경",
        "value": "0건"
      }
    ]
  },
  "하남": {
    "totalInfluencers": 3,
    "totalContents": 3,
    "totalViews": 337,
    "averageViews": 112,
    "mobileViews": 193,
    "pcViews": 144,
    "mobileRatio": 57,
    "pcRatio": 43,
    "averageMobileViews": 64,
    "averagePcViews": 48,
    "dailyData": [
      {
        "date": "2026-05-21",
        "day": "목",
        "pc": 7,
        "mobile": 12,
        "total": 19
      },
      {
        "date": "2026-05-22",
        "day": "금",
        "pc": 1,
        "mobile": 3,
        "total": 4
      },
      {
        "date": "2026-05-23",
        "day": "토",
        "pc": 0,
        "mobile": 4,
        "total": 4
      },
      {
        "date": "2026-05-24",
        "day": "일",
        "pc": 1,
        "mobile": 1,
        "total": 2
      },
      {
        "date": "2026-05-25",
        "day": "월",
        "pc": 1,
        "mobile": 2,
        "total": 3
      },
      {
        "date": "2026-05-26",
        "day": "화",
        "pc": 0,
        "mobile": 0,
        "total": 0
      },
      {
        "date": "2026-05-27",
        "day": "수",
        "pc": 1,
        "mobile": 3,
        "total": 4
      },
      {
        "date": "2026-05-28",
        "day": "목",
        "pc": 26,
        "mobile": 15,
        "total": 41
      },
      {
        "date": "2026-05-29",
        "day": "금",
        "pc": 2,
        "mobile": 3,
        "total": 5
      },
      {
        "date": "2026-05-30",
        "day": "토",
        "pc": 8,
        "mobile": 4,
        "total": 12
      },
      {
        "date": "2026-05-31",
        "day": "일",
        "pc": 5,
        "mobile": 0,
        "total": 5
      },
      {
        "date": "2026-06-01",
        "day": "월",
        "pc": 5,
        "mobile": 5,
        "total": 10
      },
      {
        "date": "2026-06-02",
        "day": "화",
        "pc": 10,
        "mobile": 7,
        "total": 17
      },
      {
        "date": "2026-06-03",
        "day": "수",
        "pc": 7,
        "mobile": 10,
        "total": 17
      },
      {
        "date": "2026-06-04",
        "day": "목",
        "pc": 9,
        "mobile": 14,
        "total": 23
      },
      {
        "date": "2026-06-05",
        "day": "금",
        "pc": 13,
        "mobile": 5,
        "total": 18
      },
      {
        "date": "2026-06-06",
        "day": "토",
        "pc": 3,
        "mobile": 17,
        "total": 20
      },
      {
        "date": "2026-06-07",
        "day": "일",
        "pc": 10,
        "mobile": 29,
        "total": 39
      },
      {
        "date": "2026-06-08",
        "day": "월",
        "pc": 2,
        "mobile": 18,
        "total": 20
      },
      {
        "date": "2026-06-09",
        "day": "화",
        "pc": 18,
        "mobile": 11,
        "total": 29
      },
      {
        "date": "2026-06-10",
        "day": "수",
        "pc": 6,
        "mobile": 7,
        "total": 13
      },
      {
        "date": "2026-06-11",
        "day": "목",
        "pc": 5,
        "mobile": 8,
        "total": 13
      },
      {
        "date": "2026-06-12",
        "day": "금",
        "pc": 0,
        "mobile": 1,
        "total": 1
      },
      {
        "date": "2026-06-13",
        "day": "토",
        "pc": 3,
        "mobile": 7,
        "total": 10
      },
      {
        "date": "2026-06-14",
        "day": "일",
        "pc": 1,
        "mobile": 7,
        "total": 8
      }
    ],
    "contents": [
      {
        "title": "하남 재수학원 추천, 공부환경이 인상적이었던 이투스247학원 하남점",
        "blogger": "gracejji",
        "date": "2026-06-03",
        "likes": 6,
        "comments": 1,
        "url": "https://blog.naver.com/gracejji/224304993758?fromRss=true&trackingCode=rss"
      },
      {
        "title": "독학재수학원 이투스247학원 하남점 추천, 하남 재수 성공의 지름길!",
        "blogger": "하루1133",
        "date": "2026-05-28",
        "likes": 103,
        "comments": 14,
        "url": "https://blog.naver.com/tjrudska82/224298459122?fromRss=true&trackingCode=rss"
      },
      {
        "title": "하남 재수 학원 이투스247미사 수능 준비 문제없어",
        "blogger": "지니지니얌2",
        "date": "2026-05-21",
        "likes": 14,
        "comments": 3,
        "url": "https://blog.naver.com/jshj9244/224292319326?fromRss=true&trackingCode=rss"
      }
    ],
    "inflowKeywords": [
      {
        "rank": 1,
        "keyword": "이투스247",
        "value": "29%"
      },
      {
        "rank": 2,
        "keyword": "하남재수학원",
        "value": "14%"
      },
      {
        "rank": 3,
        "keyword": "미사 재수독학학원",
        "value": "14%"
      },
      {
        "rank": 4,
        "keyword": "에코나우",
        "value": "14%"
      },
      {
        "rank": 5,
        "keyword": "오다이바 하루 여행",
        "value": "14%"
      },
      {
        "rank": 6,
        "keyword": "하남 학원 오픈",
        "value": "14%"
      }
    ],
    "exposedKeywords": [
      {
        "rank": 1,
        "keyword": "247공부환경",
        "value": "19건"
      },
      {
        "rank": 2,
        "keyword": "이투스247학원 하남점",
        "value": "1건"
      },
      {
        "rank": 3,
        "keyword": "하남 재수",
        "value": "0건"
      },
      {
        "rank": 4,
        "keyword": "재수학원추천",
        "value": "0건"
      },
      {
        "rank": 5,
        "keyword": "247시스템",
        "value": "0건"
      }
    ]
  }
};
