// Automatically generated by parse-reports.js
window.reportsData = {
  "하남": {
    "totalInfluencers": 3,
    "totalContents": 3,
    "totalViews": 263,
    "averageViews": 88,
    "mobileViews": 152,
    "pcViews": 111,
    "mobileRatio": 58,
    "pcRatio": 42,
    "averageMobileViews": 51,
    "averagePcViews": 37,
    "dailyData": [
      {
        "date": "2026-05-21",
        "day": "목",
        "pc": 7,
        "mobile": 12,
        "total": 19
      },
      {
        "date": "2026-05-22",
        "day": "금",
        "pc": 1,
        "mobile": 3,
        "total": 4
      },
      {
        "date": "2026-05-23",
        "day": "토",
        "pc": 0,
        "mobile": 4,
        "total": 4
      },
      {
        "date": "2026-05-24",
        "day": "일",
        "pc": 1,
        "mobile": 1,
        "total": 2
      },
      {
        "date": "2026-05-25",
        "day": "월",
        "pc": 1,
        "mobile": 2,
        "total": 3
      },
      {
        "date": "2026-05-26",
        "day": "화",
        "pc": 0,
        "mobile": 0,
        "total": 0
      },
      {
        "date": "2026-05-27",
        "day": "수",
        "pc": 1,
        "mobile": 3,
        "total": 4
      },
      {
        "date": "2026-05-28",
        "day": "목",
        "pc": 26,
        "mobile": 15,
        "total": 41
      },
      {
        "date": "2026-05-29",
        "day": "금",
        "pc": 2,
        "mobile": 3,
        "total": 5
      },
      {
        "date": "2026-05-30",
        "day": "토",
        "pc": 8,
        "mobile": 4,
        "total": 12
      },
      {
        "date": "2026-05-31",
        "day": "일",
        "pc": 5,
        "mobile": 0,
        "total": 5
      },
      {
        "date": "2026-06-01",
        "day": "월",
        "pc": 5,
        "mobile": 5,
        "total": 10
      },
      {
        "date": "2026-06-02",
        "day": "화",
        "pc": 10,
        "mobile": 7,
        "total": 17
      },
      {
        "date": "2026-06-03",
        "day": "수",
        "pc": 7,
        "mobile": 10,
        "total": 17
      },
      {
        "date": "2026-06-04",
        "day": "목",
        "pc": 9,
        "mobile": 14,
        "total": 23
      },
      {
        "date": "2026-06-05",
        "day": "금",
        "pc": 13,
        "mobile": 5,
        "total": 18
      },
      {
        "date": "2026-06-06",
        "day": "토",
        "pc": 3,
        "mobile": 17,
        "total": 20
      },
      {
        "date": "2026-06-07",
        "day": "일",
        "pc": 10,
        "mobile": 29,
        "total": 39
      },
      {
        "date": "2026-06-08",
        "day": "월",
        "pc": 2,
        "mobile": 18,
        "total": 20
      }
    ],
    "contents": [
      {
        "title": "독학재수학원 이투스247학원 하남점 추천, 하남 재수 성공의 지름길!",
        "blogger": "하루1133",
        "date": "2026-05-28",
        "likes": 103,
        "comments": 14,
        "url": "https://blog.naver.com/tjrudska82/224298459122?fromRss=true&trackingCode=rss"
      },
      {
        "title": "하남 재수학원 추천, 공부환경이 인상적이었던 이투스247학원 하남점",
        "blogger": "gracejji",
        "date": "2026-06-03",
        "likes": 6,
        "comments": 1,
        "url": "https://blog.naver.com/gracejji/224304993758?fromRss=true&trackingCode=rss"
      },
      {
        "title": "하남 재수 학원 이투스247미사 수능 준비 문제없어",
        "blogger": "지니지니얌2",
        "date": "2026-05-21",
        "likes": 14,
        "comments": 3,
        "url": "https://blog.naver.com/jshj9244/224292319326?fromRss=true&trackingCode=rss"
      }
    ]
  }
};
